### ISSUE TITLE
Altinn Storybook: On page "introduction" link to "Felles Designsystem" for core components

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#10]
- [x] In readme. Done:  https://github.com/Altinn/altinn-design-system/pull/273/commits/0cccbb3f8489fbe4a14e9e3e348971170e861f87
- [x] Rediger forsiden/introduksjonssiden. (Can´t be done until this is fixed: https://github.com/Altinn/altinn-design-system/issues/232)
- [x] Forklar på introduksjonssiden til Atlinn Storybook at dette gjelder kun komponenter som er unike for altinn, men at vi nå jobber med felles designsystem med gjenbrukbare komponenter på tvers.

**Comment by mimarz** [comment]
Do this after #1017

**Comment by mrosvik** [comment]
@Albertlarsen : Could you add a link to designsystemet.no on the introduction-page?

**Comment by Albertlarsen** [comment]
Lagt til her: https://designsystem.altinn.studio/?path=/docs/introduksjon--docs
