### ISSUE TITLE
Tokens: Nytt fargesystem

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#103]
Vi har forsøkt å forbedre fargesystemet... Det er nå definert nye semantiske farger for background, surface, border og text. [Oppsettet kan ses i Figma](https://www.figma.com/file/eeznFkuH7UletQmhN174VR/DDS---Design-Tokens?node-id=3533%3A9259&t=ZZ3ahP0R5KWTPiIZ-1). 

Fargesystemet vil fungere på samme måte som [Aksels fargesystem](https://aksel.nav.no/grunnleggende/styling/farger), men vi har i tillegg det tredje nivået for komponentspesifikke verdier.

→ [Commit i repo Altinn/figma-design-tokens](https://github.com/Altinn/figma-design-tokens/commit/c94825fadb2321d4057de5809e0466a3a8c2c7dd#commitcomment-98224590)

## Breaking changes: 

 - All tekstfarger som tidligere var `black` skal erstattes med `text-default` med mindre noe annet er spesifisert i en komponent. 

 - `interactive_components.colors.focus_outline` erstattes med `semantic.border.tab-focus.default`
 --> Alle Tab-focus farger på komponentnivå er fjernet, vi bruker i stedet en felles token (tab-focus) fra det semantiske nivået av farger. 

 - `interactive_components.colors.disabled.opacity` erstattes med `opacity.disabled`
 --> Alle disabled states skal bruke denne på semantisk nivå, de blir ikke lengre angitt på komponent-nivå.

- `Blue-950` forsvinner, erstattes med `blue-900`
- `Blue-300` erstattes med `blue-200`
- `Blue-200` erstattes med `blue-100`
- `Red-300` erstattes med `red-200`
- `Red-200` erstattes med `red-100`
- `Green-300` erstattes med `green-200`
- `Yellow 300` erstattes med `yellow-200`
- `Neutral-200` erstattes med `neutral-100`
- `Neutral-400` erstattes med `neutral-300`
- Text-area-komponent: Flyttet error-border innunder color-border
- Icon-button-komponent er avviklet (erstattes med _Quiet button with only icon_), farger for icon-button er derfor fjernet.

**Comment by TomasEng** [comment]
@mrosvik, det ser ikke ut til å være noe som heter `neutral-[tall]` i det hele tatt i den nyeste versjonen av Figma-variablene.

**Comment by mrosvik** [comment]
Beklager, det er en feil, det skulle stått:
```
grey-200 erstattes med grey-100
grey-400 erstattes med grey-300
```
