### ISSUE TITLE
`Switch` `size="small"` target size shifts content

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#1042]
We are using just the plain'old CSS box to uphold [WCAG Target size AAA](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html). 

This causes problems when you are trying to center other `small` fields with `small` `Switch`.

![Image](https://github.com/digdir/designsystem/assets/1070981/28e9616d-2b4c-4f2d-9223-b97a1581e210)

Actions:
- Test if we use the same :before/:after trick we have done on [Button](https://github.com/digdir/designsystem/blob/afbcf605542972731f11b798fc6f3c94d462199c/packages/react/src/components/Button/Button.module.css#L28)

**Comment by mimarz** [comment]
@TomasEng I am not able to reproduce this. Tried changing both root font-sizes and using small on individual component aswell as via `Fieldset`. 

Here is a sandbox with example i used for testing: https://codesandbox.io/s/charming-shadow-qvkcqr

( We also found a small bug with `NativeSelect` we'll fix 😅  )

**Comment by TomasEng** [comment]
You're right, @mimarz. We just updated the design system, and now they have all the same height, sorry for bothering you with this 😇

**Comment by TomasEng** [comment]
I was a bit too fast here. We still have these issues. But it might be that there is something in Studio overriding it. I'll have a closer look there.

**Comment by TomasEng** [comment]
Found it. Once again this happens because [the text field uses relative units](https://github.com/digdir/designsystem/blob/main/packages/react/src/components/form/Textfield/Textfield.module.css#L34), while [the switch uses absolute units](https://github.com/digdir/designsystem/blob/main/packages/react/src/components/form/Switch/Switch.module.css#L8).
If there's really no exception to the `44px` requirement, then I suggest we set the `min-height` to this value on all input components.

**Comment by mimarz** [comment]
> Found it. Once again this happens because [the text field uses relative units](https://github.com/digdir/designsystem/blob/main/packages/react/src/components/form/Textfield/Textfield.module.css#L34), while [the switch uses absolute units](https://github.com/digdir/designsystem/blob/main/packages/react/src/components/form/Switch/Switch.module.css#L8).

Yeah, I figured this was the cause of the bug, but I can't seem to be able to reproduce it in the [codesandbox I linked](https://codesandbox.io/s/charming-shadow-qvkcqr?file=/src/styles.css), even when setting the root to something like 10px.

Are you able to provide an example in a codesandbox with this bug? Would be nice to know exactly whats going wrong here so we can better test for it in the future.

**Comment by mimarz** [comment]
Maybe us using [font](https://developer.mozilla.org/en-US/docs/Web/CSS/font) shorthand is causing some unexpected behaviours here 🤔

**Comment by TomasEng** [comment]
> Yeah, I figured this was the cause of the bug, but I can't seem to be able to reproduce it in the [codesandbox I linked](https://codesandbox.io/s/charming-shadow-qvkcqr?file=/src/styles.css), even when setting the root to something like 10px.
> 
> Are you able to provide an example in a codesandbox with this bug? Would be nice to know exactly whats going wrong here so we can better test for it in the future.

Sure: https://codesandbox.io/s/awesome-gates-2dmggm?file=/src/App.js

In your example it seems like the height is overridden by the grid styling, so the `min-height` property doesn't apply.

**Comment by mimarz** [comment]
Thanks! 

We'll make sure to test for this. 

We'll probably do this as part of a broader review when streamlining the sizes in #1041
