### ISSUE TITLE
Syncronize sizing between Figma and React components

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#1075]
Update our components to use the same sizing values as in Figma. 

Let our our icons be relative to font size using `em` values. 

Some of our "input" components `Textfield`, `Textarea` etc are using `em` for, see if we can use our sizing tokens here.

**Comment by Barsnes** [comment]
@mrosvik @mimarz  Will there be any componets with size changes, or it it just removing `xsmall`?

**Comment by mimarz** [comment]
> @mrosvik @mimarz Will there be any componets with size changes, or it it just removing `xsmall`?

It was mentioned that some components might be bumped up. As in size stays the same but name is just changed from `xsmall` to `small`. Not sure which ones that was though 🤔

**Comment by Barsnes** [comment]
> > @mrosvik @mimarz Will there be any componets with size changes, or it it just removing `xsmall`?
> 
> It was mentioned that some components might be bumped up. As in size stays the same but name is just changed from `xsmall` to `small`. Not sure which ones that was though 🤔

Yeah, I think it would be best for someone to do this in figma first, and document the changes.
I saw in code that `ChipGroup` has `size?: 'xsmall' | 'small';` - which should probably be bumped, and not removed

**Comment by mimarz** [comment]
Yeah, we have an issue somewhere, where I listed all the sizes we have in code, but I cant seem to find it now 🙈

**Comment by mimarz** [comment]
@Barsnes #1003 

Yeah, typography should not be changed

**Comment by mrosvik** [comment]
This is done in Figma.
