### ISSUE TITLE
Tokens: Style Dictionary

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#108]
_If you want to use design tokens across all the platforms, you will need a token transformer to transform design tokens values.
Style Dictionary translates raw JSON data into a platform-specific format. It is available as a CLI through NPM, but can also be used like any normal node module if you want to extend its functionality._

Style Dictionary hadde spart oss for å sette opp bygg-jobber per format som vi ønsker å eksportere ut. Da hadde vi sluppet å gjøre dette i design tokens repoet.

**Comment by mimarz** [comment]
This has been solved in both packages from altinn and digdir
