### ISSUE TITLE
Unexpected Margin Under Error Message in Fieldset

### ISSUE THREAD

**Issue by nlundee** [digdir/designsystem#1081]
### Description of the bug

An unexpected margin is introduced under the error message upon toggling the error state on the fieldset. This behavior disrupts the design layout of the project, particularly impacting scenarios where there is a predefined margin between the last text field and the buttons below.

![image (3)](https://github.com/digdir/designsystem/assets/23278708/f61b3c6c-e679-44c5-8182-10d0815605dd)

### Steps To Reproduce

1.     Create a fieldset containing a text field.
2.     Intentionally toggle an error at the fieldset level.
3.     Set an error message for the text field.
4.     Observe the introduction of an empty div with an associated margin under the error message.

### Additional Information

The issue appears to be related to the CSS rule `.spacing > :not(:first-child, :empty)` within the `Fieldset.module.css` file. A [CodeSandbox](https://codesandbox.io/s/fieldset-error-top-margin-m7yztd?file=/src/App.tsx) is available for further examination.

**Comment by mimarz** [comment]
As we talked about on Slack, make sure to use the `error` prop on `Fieldset` to assign an error message for the whole fieldset :) 

Happy to help!

**Comment by nlundee** [comment]
Thanks @mimarz! 🎉 

For the sake of order, I've written a resolution explanation.

### Resolution:
Reevaluate and correct the error handling approach, acknowledging the misuse of error handling mechanisms:

- Fieldset Error State:
  - Instead of setting the error property on the fieldset to a boolean, directly assign the error message to the error property of the fieldset.
- TextField Error Message:
  - If the error pertains to a specific text field within the fieldset, set the error message on the respective text field.
  - If the error is for the entire fieldset, no additional error message needs to be set on the text field.

Recognize that the initial issue stemmed from a misunderstanding of error handling, and this resolution aims to correct the misuse of error properties.
