### ISSUE TITLE
Combobox: Develop React component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#1090]
## Related information: 

- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
- https://floating-ui.com/docs/useListNavigation
- https://codesandbox.io/s/fragrant-water-bsuirj?file=/src/App.tsx
- https://a11y-guidelines.orange.com/en/articles/autocomplete-component/
- https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs

**Comment by mimarz** [comment]
Have a look at this [type](https://github.com/equinor/design-system/blob/c6eb0b158c5fa2dff11c37d2b3571349e16c46ed/packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx#L805) and [props](https://github.com/equinor/design-system/blob/c6eb0b158c5fa2dff11c37d2b3571349e16c46ed/packages/eds-core-react/src/components/Autocomplete/Autocomplete.tsx#L186) for using generics to get typesafety on passed options object.

**Comment by mimarz** [comment]
Add property for hiding chips. This means that display and updating selected options is controlled outside. Don't forget to  disable backspace deleting selected options when hiding chips is enabled. @Barsnes
