### ISSUE TITLE
Combobox: Design component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#1091]

**Comment by mrosvik** [comment]
- [ ] Remove lines between items

**Comment by mimarz** [comment]
We are missing a style for when an option is selected in single select mode 🤔 @Febakke @mrosvik

**Comment by Febakke** [comment]
> We are missing a style for when an option is selected in single select mode 🤔 @Febakke @mrosvik

Do you mean in the dropdown list? For example that hamar is marked in some way in the example below?
<img width="417" alt="Skjermbilde 2023-12-12 kl  12 22 39" src="https://github.com/digdir/designsystem/assets/33222679/80a82fb4-e82d-477b-b436-32e39d90d039">

**Comment by mimarz** [comment]
> > We are missing a style for when an option is selected in single select mode 🤔 @Febakke @mrosvik
> 
> Do you mean in the dropdown list? For example that hamar is marked in some way in the example below? <img alt="Skjermbilde 2023-12-12 kl 12 22 39" width="417" src="https://private-user-images.githubusercontent.com/33222679/289841890-80a82fb4-e82d-477b-b436-32e39d90d039.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODA2ODcsIm5iZiI6MTcwMjM4MDM4NywicGF0aCI6Ii8zMzIyMjY3OS8yODk4NDE4OTAtODBhODJmYjQtZTgyZC00NzdiLWI0MzYtMzJlMzlkOTBkMDM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDExMjYyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzMjljNjRlZTA0MGNlN2NjNzExNTA5MmJhNTlkZTc3MjM1ZTRhZDE4YWM0ODM4MGViNDZhNzg0ZjJjZTczMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nbZAzPUAw0Y8Ev9uIJj8FKCOTWt734bL0GwGAxq3Y2M">

Jepp, after selecting an option and opening the list again, there should be an indication what option is selected. In both single and multiple select mode.
