### ISSUE TITLE
Misaligned label for checkboxes

### ISSUE THREAD

**Issue by Magnusrm** [digdir/designsystem#1110]
### Description of the bug

We encountered a bug in our project (altinn-app-frontend) where the label of the checkboxes would be misaligned caused by some css from the Designsystem being overridden by another css module from the Designsystem.

<img width="296" alt="Screenshot 2023-11-16 at 13 10 54" src="https://github.com/digdir/designsystem/assets/32294735/de4ce763-de1f-4103-9379-ef1f48cf791c">

<img width="427" alt="Screenshot 2023-11-16 at 13 11 24" src="https://github.com/digdir/designsystem/assets/32294735/332cea2c-5c14-4811-9ab5-6a557270f40c">

I was unable to find out why this happened in our project spesifically and could not reproduce the issue in codesandbox:
https://codesandbox.io/s/blue-sun-m23q3j?file=/src/App.js

### Steps To Reproduce

1. Follow documentation to get an Altinn app up and running locally: https://github.com/Altinn/app-frontend-react
2. Add a checkboxgroup with checkboxes from the Designsystem in the frontend code in some component that you are using in your app
3. See that the label is misaligned.

**Comment by mimarz** [comment]
Thanks for reporting this! 

I suspect this might be due to the nature of css modules being CSS-in-JS and thus loaded by JS in runtime and tree-shaking. 🤔 

Luckily we are moving away from css-modules, so this issue will in time resolve itself, but not sure when we'll get there. 

Either way we'll have a closer look at this to verify thats the use-case and see if we can't find a more immediate fix! 🛠

**Comment by mimarz** [comment]
Me and @Magnusrm tested importing `Label` higher up in the dom tree ("`App`") which should inject the `Label` before `Checkbox` modules `.label`. This "fixes" the problem confirming the problem relates to css being injected by js in the wrong order.

**Comment by mimarz** [comment]
This is also happens with `Search` and the search button.

**Comment by jensmo98** [comment]
@Thuneer @mimarz, I have tested the fix, and the Search component seems to works now as expected. :)

**Comment by mimarz** [comment]
Re-opened as the previous short-term "fix" broke `Radio` 😞
