### ISSUE TITLE
Link Card: Develop React component

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#1114]
LinkCard design in Figma: https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=23501%3A33528&mode=design&t=pFMkxezHjX6MVQWE-1

**Comment by mrosvik** [comment]
🤚🏻 Onhold: We should wait with `LinkCard` unntil `Card` is complete.

**Comment by mimarz** [comment]
This has been solved on `Card` by changing it to an `a` element when `href` is defined.
