### ISSUE TITLE
Export `Box`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#1125]
Export our first primitive component `Box` so that users can use it to make simple containers with our token styles.  

Evaluate if we would want to solve #1124 for `Box` as supporting correct callback types might be beneficial for this component.

**Comment by Albertlarsen** [comment]
> Evaluate if we would want to solve https://github.com/digdir/designsystem/issues/1124 for Box as supporting correct callback types might be beneficial for this component.

@mimarz  I need some examples of when you'd use asChild on Box before evaluating if we should have callback types or not
