### ISSUE TITLE
React: `Card` further development

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#1127]
List of changes to our contributed `Card` from #1009 🎉 

- [x] Replace `MediaImage` with a sub-component `Card.Media` to encourage composition
  - User should be able to provide any img or video and place it anywhere inside the card (top, center, bottom)
- [x] Rename `variant` to `color` to match pattern used for our other components
- [x] Use border style, border color and background in accordance with provided `color` variant 
- [x] Remove `BoxProps` union, set the values on `Box` according to design and `color`
  - Encourage people to use `Box` directly instead if they need this flexibility
- [x] Remove hover on `Card`, only interactive elements should have hover, which will be for separate component `LinkCard`
- [x] Move sub-components out of folders to reduce amount of barrel-files
- [x] We need more cat pictures. Gather cat photos from teams cats for examples 🐱 
- [x] Replace `Select` with `NativeSelect` in stories as `Select` is a legacy component
- Do we need to `Card.Group`? We have previously said people should just make their own grid/flex containers using tokens. I guess its used here to convey a number of cards in a group which might be important for screen readers?

**Comment by Barsnes** [comment]
Here is a cat picture, as requested in the issue 😸 
![Image](https://github.com/digdir/designsystem/assets/14057205/829f2189-8def-4fa3-80fe-cbbe0fa5158c)
