### ISSUE TITLE
DropdownMenu z-index

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#1134]
### Description of the bug

The z-index of the ```<DropdownMenu />``` component seems to not be correct: 
<img width="289" alt="image" src="https://github.com/digdir/designsystem/assets/133344438/d7ed923f-dff4-487a-8882-1e8cde60fd34">
Both the 3-dots icon, the red x, and the text fields are supposed to be under the dropdown menu

### Steps To Reproduce

See photo above.

**Comment by mimarz** [comment]
Doh, there was supposed to be one there! #500  

Looks like we forgot to add it, we'll fix this shortly!
