### ISSUE TITLE
HelpText: Border size for container gets overridden

### ISSUE THREAD

**Issue by Magnusrm** [digdir/designsystem#1153]
### Description of the bug

The border for `HelpText` components used in our project: https://github.com/Altinn/app-frontend-react, is wrong after being overridden by an internal DS css module. This seems to have happened after upgrading the DS from `0.35.0` to `0.37.0` 
This is probably related to: #1110 

![image](https://github.com/digdir/designsystem/assets/32294735/8e8252ed-6d34-4607-a192-6abdb39a8237)
![image](https://github.com/digdir/designsystem/assets/32294735/2b69fa11-8067-4bfe-8e0b-71e8a5d687a3)

### Steps To Reproduce

1. Follow documentation to get an Altinn app up and running locally: https://github.com/Altinn/app-frontend-react
2. Add a HelpText from the Designsystem in the frontend code in some component that you are using in your app
3. Open the HelpText and see that the border is 1px instead of 2px.

**Comment by Magnusrm** [comment]
this seems to be fixed by: #1163
<img width="406" alt="image" src="https://github.com/digdir/designsystem/assets/32294735/b91083d6-2022-41a1-b373-1cea74b3f8b3">

**Comment by Albertlarsen** [comment]
The border-width should be 1 px on arrow and box so I'll fix it now
