### ISSUE TITLE
Modal not wide enough, and has too much padding

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#1156]
### Description of the bug

The modal component is not wide enough to fit the content we would like to have in it. It also has too much padding. See this phtoto for reference: 
![image](https://github.com/digdir/designsystem/assets/133344438/0940430f-76e2-4009-9b96-c7c1d97c8224)
Also, found this in the code, and it seems like the max-width and padding issue is a result of this: 
![image](https://github.com/digdir/designsystem/assets/133344438/1f198020-afde-4030-ad8d-f278d25856e6)

### Steps To Reproduce

See photos above 😄

**Comment by mimarz** [comment]
Thanks for bringing this to our attention! 

If you are using entirely custom content like this we advice just not use `Modal.Content` and just use it directly inside `Modal`

- We'll move the top/bottom paddings away from `Modal` to a children selector instead.
- We had some discussion on how to handle width as we want the modal fill up the full screen under a certain width, but also have this customisable. We'll have a look at how we want to best solve this as we would like to solve this using CSS, but haven't come up with a good way yet 😅

**Comment by Barsnes** [comment]
> Thanks for bringing this to our attention!
> 
> If you are using entirely custom content like this we advice just not use `Modal.Content` and just use it directly inside `Modal`
> 
> * We'll move the top/bottom paddings away from `Modal` to a children selector instead.
> * We had some discussion on how to handle width as we want the modal fill up the full screen under a certain width, but also have this customisable. We'll have a look at how we want to best solve this as we would like to solve this using CSS, but haven't come up with a good way yet 😅

First point also relates to a bug, defined in #1116
