### ISSUE TITLE
Select virker ikke inne i modal.

### ISSUE THREAD

**Issue by larsksy** [digdir/designsystem#1180]
### Description of the bug

Når du plasserer en Select komponent inne i en Modal havner dropdown-lista med alle valgene på baksiden av modalen. 
Eksempel under:

![image](https://github.com/digdir/designsystem/assets/22899310/e65a5c79-63c5-4d74-b2b4-3a3278e93199)

### Steps To Reproduce

1. Lag en Modal komponent
2. Plasser en Select komponent inne i Modal.Content
3. Sørg for at Select komponent har noe data i options property-en
4. Trykk på nedtrekks-pilen til høyre i Select komponent

**Comment by mimarz** [comment]
Takker for tilbakemeldingen! Vi skal få noen på teamet til å ta en titt om ikke så lenge :) 

Være oppmerksom på at at vi planlegger å fase ut denne "Select" komponentene og erstatte den med en `Combobox` som er under arbeider #1126

**Comment by larsksy** [comment]
Skjønner! Kommer `Combobox` til å støtte flere valg på samme måte som `Select`?

**Comment by mimarz** [comment]
> Skjønner! Kommer `Combobox` til å støtte flere valg på samme måte som `Select`?

Jepp! Tar gjerne en titt på preview Storybook av PRen her: https://github.com/digdir/designsystem/pull/1126#issuecomment-1819129737

@Barsnes Kan bistå med spørsmål og ønsker 😄

**Comment by Barsnes** [comment]
> Skjønner! Kommer `Combobox` til å støtte flere valg på samme måte som `Select`?

Hei, som @mimarz nevnte over her, så vil den støtte `multiple` ja. 
Her er direkte link til PR previewen: [https://storybook-pr-1126.dev.designsystemet.no/?path=/docs/felles-combobox--docs](https://storybook-pr-1126.dev.designsystemet.no/?path=/docs/felles-combobox--docs)

**Comment by Barsnes** [comment]
Ser ut som den nye `Combobox` vil funke fint i modal 😄 
<img width="692" alt="image" src="https://github.com/digdir/designsystem/assets/14057205/90eef9f7-3e76-45b7-b9ea-9dda3ca2b317">

**Comment by Barsnes** [comment]
> Ser NativeSelect fungerer fint i modalen også. Kan du prøve denne @larsksy. Vi vet jo det er noen problemer med Altinn-komponentene. Vet ikke helt når vi kan fjerne Select helt fra FDS @mimarz @Barsnes ?

Hadde vært rart om `NativeSelect` ikkje hadde funka, den er jo native og legger seg ikkje i DOM på samme måte som ein `Combobox`.
`Select` fra Altinn vil brukere kunne bytte vekk frå når `Combobox` fra #1126 er merga 😄

**Comment by larsksy** [comment]
Hei igjen! Har sett over combobox og det ser ut til å passe vårt usecase veldig bra. Nå er det slik at vi er stort sett klar til prodsetting med det vi jobber med, men venter på akkurat denne biten. Vi har det selvfølgelig ikke travelt, men vil veldig gjerne være klar før jul. Er det planlagt noen release hos dere nå før juleferien?

**Comment by mimarz** [comment]
> Hei igjen! Har sett over combobox og det ser ut til å passe vårt usecase veldig bra. Nå er det slik at vi er stort sett klar til prodsetting med det vi jobber med, men venter på akkurat denne biten. Vi har det selvfølgelig ikke travelt, men vil veldig gjerne være klar før jul. Er det planlagt noen release hos dere nå før juleferien?

Vi ønsker å få det ut før jul ja :) Vi er i prosessen funksjonell og DX testing nå, samt litt bugfiksing. Håper å få det ut snarest ja!
