### ISSUE TITLE
Dropdown.Items blir feil ut når de ikke er wrappet av Dropdown.Group

### ISSUE THREAD

**Issue by larsksy** [digdir/designsystem#1181]
### Description of the bug

Når Items inne i en dropdown ikke er wrappet av en `Dropdown.Group` komponent beholder liste-elementene `list-style` property-en siden `list-style: none` kun kommer fra styling-klassen til `Group` komponenten.

Eksempel kode: 

```
<DropdownMenu anchorEl={ref.current} open={open}>
     <DropdownMenu.Item>
         Item1
    </DropdownMenu.Item>
    <DropdownMenu.Item>
         Item1
    </DropdownMenu.Item>
</DropdownMenu>
```

Koden over produserer følgende resultat:

![image](https://github.com/digdir/designsystem/assets/22899310/a4d4ba44-8c69-4c25-9749-d5b7b27e4f11)

Samme kode med Groups: 

```
<DropdownMenu anchorEl={ref.current} open={open}>
    <DropdownMenu.Group>
        <DropdownMenu.Item>
            Item1
        </DropdownMenu.Item>
        <DropdownMenu.Item>
            Item1
        </DropdownMenu.Item>
    <DropdownMenu.Group>
</DropdownMenu>
```
Dette produserer følgende resultat:

![image](https://github.com/digdir/designsystem/assets/22899310/6323e5fe-9174-45ad-a984-6111d73125a5)

### Steps To Reproduce

1. Lag en dropdown komponent
2. Legg inn en Item i dropdown uten å bruke Group
3. Sjekk elementene i dropdown-lista

**Comment by mimarz** [comment]
Takk for rapportering av funnet! 

Vi skal få noe på teamet til å ta en titt om ikke så lenge :)
