### ISSUE TITLE
Textfield - Aria-describedby always in use

### ISSUE THREAD

**Issue by tina-ahm** [digdir/designsystem#1182]
### Description of the bug

We used [W3C Markup Validation Service](https://validator.w3.org/) to validate our code and found an error in the Textfield component.

Here is the error:
![Screenshot 2023-12-04 at 16 03 12](https://github.com/digdir/designsystem/assets/150332945/97dd012b-76eb-4cb7-8e72-81dfa6571d34)

We are using the Textfield component with a label and no description, and the error states that we have a "Bad value for aria-describedby". We can see in the Textfield component that [aria-describedby](https://github.com/digdir/designsystem/blob/0d1d861a0c0fcb08fec039ac329247e741a820dd/packages/react/src/components/form/Textfield/Textfield.tsx#L167C13-L167C13) is always sent in as a property to its child, the <input> tag.

### Steps To Reproduce

1. Add Textfield component
2. Add label (do not add description)
3. Copy the HTML
4. Run the HTML through [this validator](https://validator.w3.org/)

**Comment by mimarz** [comment]
Good catch. Thanks for letting us know! 

We'll have a look at it in not long hopefully. I am suspecting its one of the nil checks in our [useFormField](https://github.com/digdir/designsystem/blob/0d1d861a0c0fcb08fec039ac329247e741a820dd/packages/react/src/components/form/useFormField.ts#L70) hook 🤔
