### ISSUE TITLE
The Rotate style functionality does not work when adding a <div> between Accordion.Item and Accordion.Header

### ISSUE THREAD

**Issue by JamalAlabdullah** [digdir/designsystem#1196]
### Description of the bug

In Team-studio, we usean `Accordion `in a 'lage' page. We display the `Accordion.header` and `NavigationMenu` in one block by using a` <div>` that wraps both of them in flex style. However, this `<div>` prevents the rotate functionality from working, causing the `accordion `arrow to always point down. We are wondering if the design team can address this issue so that we can use a `<div>` between `Accordion `elements.

This video with` <div>`:
https://github.com/digdir/designsystem/assets/90609090/66cd3ffc-52dd-4a30-9d38-8fc8ae2a84dd

This one without `<div>`:
https://github.com/digdir/designsystem/assets/90609090/1d62594a-534b-4eef-8b62-77f7474310df

Here is link to our issue :
https://github.com/Altinn/altinn-studio/issues/11484

### Steps To Reproduce

1. Go to `lage `page .
2. open and close the accodrion , notice that the arrow still pointed down.

**Comment by mimarz** [comment]
Thanks for reporting this! 

Having a quick look, it looks like this is due to the css selector for flipping the chevron expecting elements in a specified order: https://github.com/digdir/designsystem/blob/5d4c040f511c5e7edcb099cde9c62e98dd11ec2f/packages/react/src/components/Accordion/Accordion.module.css#L146

**Comment by Barsnes** [comment]
> Thanks for reporting this!
> 
> Having a quick look, it looks like this is due to the css selector for flipping the chevron expecting elements in a specified order:
> 
> https://github.com/digdir/designsystem/blob/5d4c040f511c5e7edcb099cde9c62e98dd11ec2f/packages/react/src/components/Accordion/Accordion.module.css#L146
> 
> The other selectors should also be revised to ensure they don't break if something is used like this.

I'll get on this issue. We can make another issue to go over other selectors that might need changing
