### ISSUE TITLE
Minor bug: <Label/> and <Paragraph/> not same size/aligned

### ISSUE THREAD

**Issue by hegeaal** [digdir/designsystem#1199]
### Description of the bug

Not sure if I'm using the components how they are intended, but it would be great if `<Label/>` and `<Paragraph/>` could be on the same line when used next to each other 🥹 Not sure why they act like this because they have the same font size 🤔

![image](https://github.com/digdir/designsystem/assets/48259307/8a804e99-1f05-4e02-8474-995aef7b3d7b)

### Steps To Reproduce

When using `<Label/>` and `<Paragraph/>` next to each other they are a bit unaligned. 

![image](https://github.com/digdir/designsystem/assets/48259307/448115a2-ccad-41fa-b91a-48295073f7ac)
![image](https://github.com/digdir/designsystem/assets/48259307/126a3767-2e97-46c8-b3cc-38caf836d62e)

**Comment by Barsnes** [comment]
Hi, thanks for the issue!
`Label` is usually meant to be used with form elements, but it is not restricted to. [ref](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)
We will have to look a bit further into this, but @mrosvik or @Febakke might be able to help you out  in the meantime.

**Comment by hegeaal** [comment]
> I made a CodeSandbox with a possible solution to your problem, but this does not use labels. https://codesandbox.io/p/sandbox/async-breeze-rnmmn5 Since you have not connected to `Label` to anything, it might cause WCAG errors. Here is how I solved it in the sandbox:
> 
> ```tsx
> <Paragraph>
>     <strong>E-post</strong>: data@mail.com
> </Paragraph>
> ```

Okei perfekt! Takk for svar 😄

**Comment by Barsnes** [comment]
> > I made a CodeSandbox with a possible solution to your problem, but this does not use labels. https://codesandbox.io/p/sandbox/async-breeze-rnmmn5 Since you have not connected to `Label` to anything, it might cause WCAG errors. Here is how I solved it in the sandbox:
> > ```tsx
> > <Paragraph>
> >     <strong>E-post</strong>: data@mail.com
> > </Paragraph>
> > ```
> 
> Okei perfekt! Takk for svar 😄

Berre hyggelig 😄
