### ISSUE TITLE
Font: Replace FF-DIN and Altinn-DIN with Inter in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#12]
Description
Because of lisens issues and lacking functionality on FF DIN and Altinn-DIN we have to find one font that we can use on all our products. After reviewing different potensial Open Source fonts we landed on [Inter](https://rsms.me/inter/) as the best solution.

The font should be replaced in all components and texts in Figma. Inter is larger than the previous used DIN-font, so we should make sure it aligns correct in different contexts, and that the vertical space inside containers is correct. 

In scope

- [ ] Define the different weights and sizes we need to replace FF DIN
- [ ] Test how the different pages will look/behave after a font change
- [ ] Replace all fonts in Figma

Relevant:
[Change the font on relevant pages/systems in code](https://github.com/digdir/designsystem/issues/13)

**Comment by mimarz** [comment]
Meeting 31.10.23

New design uses Inter so this will gradually be phased out
