### ISSUE TITLE
FieldSet complains about <p> when sending in a ReactNode error via props

### ISSUE THREAD

**Issue by DanRJ** [digdir/designsystem#1202]
### Description of the bug

According to the [documentation regarding the FieldSet ](https://storybook.designsystemet.no/?path=/docs/felles-fieldset--docs) the error prop is of type ReactNode, however an error occurs when passing on a ReactNode that is using `<ul>` / `<p>` / `<h4>`.

Just an abbreviated example:
```
<FieldSet
    error={<h4>Hello</h4>}
/>
```

The following error occurs:
![image](https://github.com/digdir/designsystem/assets/3437949/5aab7cdc-1d82-4644-ac2e-c9be25197045)

We suspect the component wraps the Error in a `<p>`, which in our humble opinion is wrong considering it accepts a ReactNode.
We are implementing the following UU criteria: [3.3.3](https://www.uutilsynet.no/wcag-standarden/333-forslag-ved-feil-niva-aa/118) which recommends [G83 ](https://www.w3.org/TR/WCAG20-TECHS/G83)and G83 in turn recommends showing a list of fields where an error has occurred.

It is not currently possible to have a `<ul>`, `<dl>` or any other form for list in the error prop.

### Steps To Reproduce

1. Add `<FieldSet error={...}>`
2. Pass `<p>hello</p>` to the error prop
3. See that an error occurs in console

**Comment by mimarz** [comment]
Thanks for reporting this! 

We'll fix this shortly :)
