### ISSUE TITLE
Accordion should work as an uncontrolled component

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#134]
The `Accordion` component now relies on the consumer to set its expanded state. This is not convenient unless if the state is dependent on factors provided by the consumer. Therefore, the expansion and closing of the accordion should be handled internally if the `open` property is not set.

**Comment by mimarz** [comment]
This is supported in the new `Accordion` we released here: https://github.com/digdir/designsystem/releases/tag/%40digdir%2Fdesign-system-react%400.12.0
