### ISSUE TITLE
Specification for: Actionbar

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#141]
### Related issues or relevant information?

![image](https://user-images.githubusercontent.com/1464915/217736272-511ef6ab-520d-4996-b530-33c32165eeef.png)

### Design tasks

- [ ] Design is fully specified in Figma
  - [ ] Design component with all relevant states
  - [ ] Do a accessibility test of the sketches
  - [ ] Functionality/animation is described and prototyped if relevant    
  - [ ] If there are used any svgs in this component is it available for the developer? [Link]
  - [ ] Link to Figma design: [Link]
  - [ ] Pasted screenshot from Figma below :point_down::skin-tone-2:  

### Development Tasks

- [ ] Implement in Storybook
- [ ] Make sure all variants/properties is possible to turn on/off
- [ ] Make sure the component is usable across different breakpoints/screen sizes

### Accessibility tasks

- [ ] WCAG-review

**Comment by mrosvik** [comment]
Should this be moved to Team Autorisasjon? @hannekristin @allinox

**Comment by allinox** [comment]
@mrosvik 
We already have an issue for this 😊

**Comment by mrosvik** [comment]
Closing this issue since it is specific for authorization. [Accordion](https://github.com/orgs/digdir/projects/3?pane=issue&itemId=18766458) will instead be developed as a common component in Felles Designsystem, since it is simpler, more generic and can be used by many teams.
