### ISSUE TITLE
Small icon buttons are smaller than icon buttons with text

### ISSUE THREAD

**Issue by Albertlarsen** [digdir/designsystem#187]
### Description of the bug

Picture of bug shows difference in size between quiet icon button and quiet icon button with text even when they have ButtonSize.Small
![image](https://user-images.githubusercontent.com/31471142/221841943-25ae94c6-9e92-4a47-a1cd-b6173433b561.png)

### Steps To Reproduce

Picture of bug shows difference in size between quiet icon button and quiet icon button with text.

**Comment by mrosvik** [comment]
I think the bug is that width is set instead of height. There should not be a fixed width on buttons, only fixed height. Can someone change width to height in the code? :) 

@Albertlarsen @mimarz 

https://user-images.githubusercontent.com/1464915/224635275-c70fe93c-dcf1-446b-9a05-e98ee03d1a1e.mov

**Comment by Albertlarsen** [comment]
I'll fix

**Comment by bjosttveit** [comment]
Its a much better size now, but now its not round when it only has an icon. Is that intended? I think it would look better if it was round.

![image](https://user-images.githubusercontent.com/47412359/226849974-578ad4a5-a2fa-47bf-8c68-26f9e5087bd4.png)

**Comment by mrosvik** [comment]
It is supposed to be round. Maybe we have to do something with the padding left and right? 

![Image](https://user-images.githubusercontent.com/1464915/227017887-ad69a58f-5a97-42b1-b6a0-6f4965b8e157.png)

**Comment by mrosvik** [comment]
In Figma we have used 12px padding left and right for small buttons with text (and icon). Small buttons with only icon have only 6px. Maybe we need a specific token for only-icon-spacing?

**Comment by mimarz** [comment]
fixed in #265
