### ISSUE TITLE
Create popover panel component

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#190]
There is a `PopoverPanel` component in Altinn's design system. We should make one in the common design system, but it should be based on our own, already existing `Popover` component.

**Comment by mimarz** [comment]
Is this longer relevant? @TomasEng  Not sure what this is 🤔

**Comment by TomasEng** [comment]
It's about this one: https://designsystem.altinn.studio/?path=/docs/components-panel-popoverpanel--docs
I don't think we need this at the moment. I see that the design for the new Popover component has background colours implemented, so it will be quite similar.

**Comment by mimarz** [comment]
The new `Popover` should covers this use-case now.
