### ISSUE TITLE
Move circular progress component from Altinn's design system

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#194]
Is this something we want in the common design system, or is it an Altinn specific component? If the latter is the case, nothing needs to be done.

```[tasklist]
- [ ] Move component code and unit tests
- [ ] Refactor CSS classes (we are not using the BEM convention)
- [ ] Create Storybook MDX file
```

**Comment by mimarz** [comment]
Is this the same as the Spinner that was added in #162?

**Comment by TomasEng** [comment]
> Is this the same as the Spinner that was added in #162?

No, this is a diagram component that is meant to visualize the completeness of some process. There is a demo here: https://designsystem.altinn.studio/?path=/docs/components-circularprogress--simple-example

**Comment by mimarz** [comment]
> > Is this the same as the Spinner that was added in #162?
> 
> No, this is a diagram component that is meant to visualize the completeness of some process. There is a demo here: https://designsystem.altinn.studio/?path=/docs/components-circularprogress--simple-example

I see! Maybe the `Spinner` and `CircularProgress` can be conformed together somehow. They look the be the same thing just determinate and indeterminate version of one and another?

**Comment by mimarz** [comment]
Meeting 31.10.23

We are satisfied with just `Spinner` for now
