### ISSUE TITLE
Move page component from Altinn's design system

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#196]
Is this something we want in the common design system, or is it an Altinn specific component? If the latter is the case, nothing needs to be done.

```[tasklist]
- [ ] Move component code and unit tests
- [ ] Refactor CSS classes (we are not using the BEM convention)
- [ ] Create Storybook MDX file
```

**Comment by Albertlarsen** [comment]
This should be waited with until Marianne is finished speccing this task #143

**Comment by mrosvik** [comment]
Utgår. Page blir ikke en komponent i felles designsystem.
