### ISSUE TITLE
Tokens: Endre NPM pakken til å peke mot designsystemet

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#21]
- [ ] Endre navn på NPM pakken til "@digdir/design-system-tokens" og publisere
- [ ] Markere gamle NPM pakken som depricated og peke til nye NPM pakken
- [ ] Oppdatere pakke-avhengigheten i storybook for designsystemet
- [ ] Oppdatere dokumentasjon i storybook: Endre navn i shield/badge og fikse path i tokens-table komponenten

**Comment by mrosvik** [comment]
@Thuneer Er denne fortsatt relevant eller kan den lukkes?

**Comment by Thuneer** [comment]
Nope, denne kan lukkes.
