### ISSUE TITLE
Remove use of `any` from code

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#223]
There is a lot of use of the [any](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any) type in the code today. This needs to be removed as its a source of bugs, hard to maintain and completely negates the benefits of using Typescript. 

```[tasklist]
### Tasks
- [ ] https://github.com/digdir/designsystem/issues/225
- [x] Remove use of `any` from packages
```

**Comment by TomasEng** [comment]
The only ramaining `any` is within the `Table` component. There is no straightforward way to replace it, but we will refactor this component anyways.
