### ISSUE TITLE
RadioButton and Checkbox size extra-small off-centers checkmark

### ISSUE THREAD

**Issue by Magnusrm** [digdir/designsystem#250]
### Description of the bug

The extra small version of checkbox and radios makes the checkmark move out of center of its button / box.
Component:
<img width="130" alt="image" src="https://user-images.githubusercontent.com/32294735/225898936-2351e351-787b-479b-b529-a9c06506278d.png">
<img width="228" alt="image" src="https://user-images.githubusercontent.com/32294735/225899019-96ecdc50-aae3-46a0-9205-8d32870447cd.png">
Figma:
<img width="131" alt="image" src="https://user-images.githubusercontent.com/32294735/225899219-8dd425f6-fc1e-4018-a978-ea8a0f08fd09.png">
<img width="124" alt="image" src="https://user-images.githubusercontent.com/32294735/225899287-4af3fef0-ccb5-4b08-9cb3-5c942e82f754.png">

### Steps To Reproduce

1. go to https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-radiogroup--kompakt#kompakt-visning
2. click radiobutton in compact mode

1. go to https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-checkboxgroup--kompakt#kompakt-visning
2. click checbox in compact mode

**Comment by bjosttveit** [comment]
Not directly related, but is the focus outline supposed to be around the entire label? If so should it have more spacing between the text and the outline? Its looks a bit tight now in my opinion.

![image](https://user-images.githubusercontent.com/47412359/226850967-f27ee905-3181-4f70-9da3-ab61a26f874b.png)

**Comment by mrosvik** [comment]
Fixed for radio buttons, still a problem for small checkboxes.
