### ISSUE TITLE
Multiple select handles long option labels poorly

### ISSUE THREAD

**Issue by bjosttveit** [digdir/designsystem#274]
### Description of the bug

If an option label is longer than the width of the multiple select, it will overflow into multiple lines like this:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/47412359/228517706-f27eb5d2-754a-447f-83d0-6b5c1e2e0f1d.png">

### Steps To Reproduce

Set an option label to something like:
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non velit ut justo rutrum ultrices. Quisque a eleifend dolor. Maecenas non faucibus erat.
```

**Comment by mimarz** [comment]
This is solved by #1090

Height of `Chip` inside `Combobox` will grow in height to match content.
