### ISSUE TITLE
Create Accordion React component

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#293]
#292 needs to be finished before starting this.

### Specification
- [x] Adhere to pattern: https://www.w3.org/WAI/ARIA/apg/patterns/accordion/
- [x] Header should be a button element (no rich text)
- [x] Controlled / uncontrolled state
- [x] Support forwardRef 
- [x] Support Compound components (Item, Header, Content)
- [x] Document Typescript props using JSDoc
- [x] Use new semantic tokens from `@digdir/design-system-tokens`
- [x] Define component level css variables with unique prefix

**Comment by haabe** [comment]
Suggestion: Use the [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) tags for markup

<details>
<summary>Expand me!</summary>
I'm expanded
</details>

```
<details>
<summary>Expand me!</summary>
I'm expanded
</details>
```
