### ISSUE TITLE
Select: ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by bjosttveit** [digdir/designsystem#314]
### Description of the bug

When using a select (either single or multi) and the size is not fixed (for example using flex-grow: 1 to scale it), you get an error when right clicking either select, and for single select it also happens when you select something and quickly open it again.

Example video shows it not happening with language selector (fixed width) but in the form components (flex-grow).

https://user-images.githubusercontent.com/47412359/233988418-8e168f17-3bac-4c3d-a52e-bb44b7a8637e.mov

Note: this only happens in the dev-server, not when serving a static build. The error probably still occurs, but you will not see any error message as in the video. Cypress still complains about it, even though this does not use a dev-server:

![image](https://user-images.githubusercontent.com/47412359/234016262-e0f1fa11-db54-406c-8a2b-b11e1a210b4d.png)

### Steps To Reproduce

.

**Comment by TomasEng** [comment]
@bjosttveit, is this still happening with the latest version of the design system? I observed this recently in Studio, but then I updated the design system (with the latest version of Floating UI), and I didn't see it anymore.

**Comment by bjosttveit** [comment]
We have not updated yet, but i'll let you know 🤝

**Comment by TomasEng** [comment]
I see that it occasionally shows up again. I'll see what I can do.

**Comment by bjosttveit** [comment]
Forgot to respond, sorry 😅  But you are correct, it still shows up, but maybe not as consistently as before.
