### ISSUE TITLE
Schema components need more flexible text properties

### ISSUE THREAD

**Issue by TomasEng** [digdir/designsystem#32]
In order to add custom formatting and components to labels, descriptions etc., it is not sufficient to take in these properties as simple strings. I suggest changing their type to `React.ReactNode`. This will make it possible to use the design system components in the preview mode of the form builder in Altinn Studio:
![Image](https://user-images.githubusercontent.com/29770305/210950743-14943481-5531-4503-ad2c-7db38e93a34a.png)

**Comment by TomasEng** [comment]
I think we can ut this on hold as this design in Altinn Studio is about to change, and there are currently no other requests for this functionality as far as I am aware.

**Comment by mimarz** [comment]
All text fields in the new `Textfield` are now  `ReactNode` :)
