### ISSUE TITLE
Use our own Typography components in Storybook

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#327]
Dependant on #324 

Storybook has support for using our own react components to override the different typography elements that are generated when using stories and when markdown is written.

Mdx2 did however introduce a breaking change where not all elements are correctly replace with your own defined components.
 
Suggest we have a look at this again when mdx2 fixes the bug and our Typography components is ready :) 

Notes:
- Guide: https://storybook.js.org/docs/react/writing-docs/autodocs#working-with-custom-mdx-components
- Breaking change in mdx2: https://storybook.js.org/docs/react/writing-docs/mdx#breaking-changes

**Comment by Barsnes** [comment]
This was resolved in #973

**Comment by mimarz** [comment]
We will move away from using our own components in Storybook as it interfers with several built-in features and we need to make our own components if we want to mimic the same features. This creates more overhead and maintenance for the team we don't want atm
