### ISSUE TITLE
npmjs package for Digdir illustrations

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#328]
We got a feature request during the designsystem-sync on 26 april 2023 if illustrations for Digdir could be exported as svg files and distributed as package on npmjs.org under `@digdir`. 

Maybe not in the scope for what the FDS should support and maintain but could be beneficial for DigDir? 

Suggest we have a talk about what our stance on this is and provide a reply or recommendation

**Comment by mrosvik** [comment]
Not in the scope for Felles Designsystem.
