### ISSUE TITLE
Component: Select (combine multiselect and single select in Figma and fix size issue)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#34]
![Image](https://user-images.githubusercontent.com/1464915/212258714-1646e5f6-5c52-42ca-9a24-c4d96f60df44.png)

**Comment by mrosvik** [comment]
Har oppdatert Select-komponenten i Figma. Vil dere se over at alt ser riktig ut? @Febakke @Thuneer 

https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7538%3A45627&t=xlYDTn7VXmpckqPy-1

**Comment by Febakke** [comment]
@mrosvik 
Ser bra ut! 🙌 Mye bedre å samle dette på en side. 
Eneste jeg fant var ulikheten på small og medium på default og hover her med tanke på den "slett alt" krysset. 

![Image](https://user-images.githubusercontent.com/33222679/212260713-258e690a-8c7d-4900-b630-81f619ed8161.png)
