### ISSUE TITLE
Justering av overskrifter og innhold i tabell

### ISSUE THREAD

**Issue by xmrsa** [digdir/designsystem#388]
### Description

Justeringen av kolonneoverskriftene burde være på linje med feltene i tabellen under. Det er jo allerede avstand mellom kolonnene i tabellen, så da burde vel avstanden mellom tekstene i overskriftene ha samme størrelse på margene? Det er kun den første kolonnen som er justert slik jeg forventer. De andre kolonnene har et innrykk i forhold til innholdet i tabellen.

![image](https://github.com/digdir/designsystem/assets/42466346/b8efd422-3d55-4473-ae5e-caf8db04c156)
 
 Kanskje er ikke dette noe det går an å styre, men jeg spør likevel.

**Comment by mrosvik** [comment]
Takk for rapportering, vi skal se på dette!
