### ISSUE TITLE
Mer kompakt visning av knappene Lagre og Slett

### ISSUE THREAD

**Issue by xmrsa** [digdir/designsystem#389]
### Description

Hvis man har litt flere kolonner i en tabell, tar knappene opp uforholdsmessig mye plass.

Jeg ønsker meg en mulighet for å f.eks. få knappene under hverandre hvis man vil (eller kunne styre bredden på knappekolonnen med "width"?) såfremt det er forenelig med UU-krav.
 
![image](https://github.com/digdir/designsystem/assets/42466346/c02925cd-e081-4140-9341-ef5c7b8f992a)

**Comment by xmrsa** [comment]
Jeg ser av visningen når man forstørrer skjermbildet mye, at man da får opp en annen variant av de to knappene som er langt mer kompakt. Både uten teksten og med ikonene under hverandre. En slik framstilling kan være ønskelig i selve tabellen også. 
![image](https://github.com/digdir/designsystem/assets/42466346/3094a258-5b5b-438e-b496-411192c527df)

**Comment by olemartinorg** [comment]
Jeg skyter inn at det ikke er sikkert det er noe galt med knappene her i seg selv (som kommer fra designsystemet), men kanskje vi må tenke frem en god variant som er litt mer plassbesparende. Godt mulig dette issuet skal flyttes til [Altinn/app-frontend-react](https://github.com/Altinn/app-frontend-react/), men vi får vurdere først om det trengs noen nye måter å vise knappene på. Tar meg friheten til å tagge @Febakke og @sophiearntsen for å høre hva dere tenker.

**Comment by mrosvik** [comment]
Hei! Veldig enig, synd at knappene her stjeler så mye av plassen her.

[Knappene fra designsystemet](https://digdir.github.io/designsystem/?path=/docs/kjernekomponenter-button--docs) skal støtte å bruke kun ikon også på store skjermer, det tror jeg ville vært den beste løsningen her. Slett-ikonet (søppelbøtta) og Rediger (blyanten) er jo ganske kjente symboler, og når de står på siden av hverandre her, vil det også forsterke at det er trykkbare knapper. Brukes et mindre kjent symbol bør tilhørende tekst eksistere. 

En ulempe er at "Lagre og lukk" ikke vises når raden er i redigeringsmodus, men så lenge dere har "Lagre og lukk" som egen knapp i bunnen vil jeg tro det holder. :) Test gjerne på noen brukere og del innsikten! <3 

<img width="704" alt="image" src="https://github.com/digdir/designsystem/assets/1464915/ecb53eb5-2b19-471c-a000-73e2398864d8">

**Comment by xmrsa** [comment]
Denne saken bør antakelig sees i sammenheng med denne som jeg dumpet borti: https://github.com/Altinn/app-frontend-react/issues/1018
