### ISSUE TITLE
Select: Input is clipped on our smallest viewport@375

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#398]
![Image](https://github.com/digdir/designsystem/assets/1070981/e2809e3d-490e-4f93-ae51-7f76ed561a36)

**Comment by TomasEng** [comment]
I think this is an issue in the Storybook example only. There is a wrapper with a fixed width because the component doesn't look well with full with on large screens.

**Comment by mimarz** [comment]
This is solved by #1090
