### ISSUE TITLE
Component: Lage grid komponenter

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#41]
- [ ] Kalle inn til møte med DS-teamet for å diskutere hvordan komponentene skal se ut
- [ ] Legge ut forslaget i design-systen slack kanalen

**Comment by mrosvik** [comment]
Dette blir vel ikke komponenter, men utilities-klasser som kan brukes i layout-oppsett?

**Comment by mrosvik** [comment]
Etter arbeidsmøte med @Thuneer  :

Dette kan bli 3 komponenter: 
- Container
- Row
- Col

..for å gjøre det enklere å definere layouten "riktig".

![Image](https://user-images.githubusercontent.com/1464915/215081716-2431dc4d-4ff2-49d9-9f25-510cdde287c7.png)


@Thuneer diskuterer dette forslaget videre med @TomasEng

**Comment by mimarz** [comment]
This can easily be solved by using css grids now. We might look at this later when deciding on primitives
