### ISSUE TITLE
Themable knapper i henhold til brand

### ISSUE THREAD

**Issue by hegeaal** [digdir/designsystem#440]
### Description

FDK ønsker seg gjerne knapper med brand-farger da fargene som finnes i dag ikke passer med headeren vår:-)

**Comment by mrosvik** [comment]
Hei :) Kunne vi tatt et møte sammen og diskutert hvordan vi løser dette? Ta med Mateus?

**Comment by hegeaal** [comment]
Hallo! Ja, det kan vi! Dette er forsåvist ikke en feature som haster da vi har funnet en måte å løse det på med den knappen som er i designsystemet i dag. Forstod riktignok at denne skal bli erstattet på et tidspunkt, så da vil det jo være aktuelt. :-) @mrosvik

**Comment by mrosvik** [comment]
Vi har hatt et møte i dag og kommet frem til: 

- FDK (@matfuru) tar kontakt for å sette opp FDK sitt fargesystem i tokens når de er klar, sammen med @mrosvik  
- Button settes opp med action primary og action secondary.

Saken legges i backlog inntil videre.

**Comment by mrosvik** [comment]
------

Will be resolved by: 
https://github.com/digdir/designsystem/pull/560

------

The brand-set can override primary and secondary action colors:

![image](https://github.com/digdir/designsystem/assets/1464915/e40b036b-4a0d-432e-abdc-d141fb379ab2)
