### ISSUE TITLE
Storefront: Analyseverktøy

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#446]
[Amplitude](https://amplitude.com/get-started?utm_source=google-ads&utm_medium=cpc&utm_campaign=Search_EMEA_EN_Brand_Growth&utm_content=147981460554&utm_term=amplitude&gad=1&gclid=Cj0KCQjwjryjBhD0ARIsAMLvnF-Yp-87Y-wA0BIInoyBPSPh5qJUE_1plDQ1P18bNkfksafDzxZB7_IaArYmEALw_wcB)?

**Comment by mimarz** [comment]
We are using Vercels built-in analysis tool for this
