### ISSUE TITLE
Docs: Is it possible to sync guidelines text from Figma to Storybook markdown?

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#45]

**Comment by mrosvik** [comment]
Etter møte med @Thuneer (23.01.23) konkluderer vi med at vi ikke prioriterer dette nå. Det kommer til å være mye knot å få samkjørt stylede lenker, lister, overskrifter, paragrafer, med mer. I tillegg blir det problematisk å få vist tekst blandet med komponent-eksempler slik vi ønsker. 

Vi går i stedet for denne løsningen:
1) Designere og innholdsdesignerer lager retningslinjer i Figma
2) Når retningslinjene er ferdigstilt og kvalitetssikret legger vi dem over i Storybook og _**fjerner**_ dem fra Figma, slik at vi kun har dokumentasjonen et sted. Fra Figma kan vi i stedet lenke til den aktuelle siden i Storybook for retningslinjer. Høres det greit ut?

FYI. @dortedrange @Febakke @Ildest

**Comment by Ildest** [comment]
Hei Marianne!

Forstår jeg det riktig, at vi da skal fortsette å jobbe med retningslinjene bare i Figma, enn så lenge?

Hilsen

Gørild Døhl
Jobber med innholdsdesign og klarspråk
***@***.***
48 24 05 96

Fra: Marianne Røsvik ***@***.***>
Dato: tirsdag, 24. januar 2023 kl. 09:02
Til: digdir/designsystem ***@***.***>
Kopi: Døhl, Gørild ***@***.***>, Mention ***@***.***>
Emne: Re: [digdir/designsystem] Docs: Is it possible to sync guidelines text from Figma to Storybook markdown? (Issue #45)
[ Ekstern e-post ]

Etter møte med @Thuneer<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FThuneer&data=05%7C01%7C%7C653c427ab689443969c308dafde153e3%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638101441471629594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5KCXoJKBLHgyIPLq%2BVZ5S1xY%2B1CwXgZfLW1SMKUuddM%3D&reserved=0> (23.01.23) konkluderer vi med at vi ikke prioriterer dette nå. Det kommer til å være mye knot å få samkjørt stylede lenker, lister, overskrifter, paragrafer, med mer. I tillegg blir det problematisk å få vist tekst blandet med komponent-eksempler slik vi ønsker.

Vi går i stedet for denne løsningen:

  1.  Designere og innholdsdesignerer lager retningslinjer i Figma
  2.  Når retningslinjene er ferdigstilt og kvalitetssikret legger vi dem over i Storybook og fjerner dem fra Figma, slik at vi kun har dokumentasjonen et sted. Fra Figma kan vi i stedet lenke til den aktuelle siden i Storybook for retningslinjer. Høres det greit ut?

FYI. @dortedrange<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdortedrange&data=05%7C01%7C%7C653c427ab689443969c308dafde153e3%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638101441471629594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oIe5v3ftQCigWsif7Gw7uLhP7U6mo5UC9L9xL5ns74I%3D&reserved=0> @Febakke<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFebakke&data=05%7C01%7C%7C653c427ab689443969c308dafde153e3%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638101441471629594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rNndu0kVmkV1QVsLZIQ3MXYz2odF8tkXwLUIVhHyQpg%3D&reserved=0> @Ildest<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIldest&data=05%7C01%7C%7C653c427ab689443969c308dafde153e3%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C638101441471629594%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7XPaaubyt1d2iX4N3uAeizXW%2B7bCIlp2Qp4PFh82qzs%3D&reserved=0>

**Comment by mrosvik** [comment]
Ja, det stemmer @Ildest
