### ISSUE TITLE
Figma: Add interactivity to completed components

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#461]
All components should be ready for prototyping by our users. Set up components as described here: https://help.figma.com/hc/en-us/articles/360061175334-Create-interactive-components-with-variants

**Comment by mimarz** [comment]
solved as part of #501

**Comment by mrosvik** [comment]
@Febakke Looks like textField is missing interactivity 

https://github.com/digdir/designsystem/assets/1464915/b8efa986-fbb6-4715-a493-2a5bc20bf1c8

**Comment by mrosvik** [comment]
Sorry, my mistake, this example was using incorrect component. Fixed now. 

https://github.com/digdir/designsystem/assets/1464915/9e8dca0f-a7a6-4d18-b75e-c69f039fd02a
