### ISSUE TITLE
RadioButton not visible with Playwright

### ISSUE THREAD

**Issue by lasseklovstad** [digdir/designsystem#465]
### Description of the bug

When using [playwright](https://playwright.dev/) to automate testing of our Altinn survey platform we can't click radio buttons because they are not visible.
Altinn used to use material ui radiobuttons that worked fine with our playwright tests. But when we bump our version they are not visible and therefor not clickable if. We can force click but this is not good practise and should be avoided.

Here is error message from playwright:
![image](https://github.com/digdir/designsystem/assets/43168787/5a66ee1c-a9f9-4d46-ad9c-d53c3282df38)

The reason is because the radio input html element has dimensions 0 x 0 as seen here:
![image](https://github.com/digdir/designsystem/assets/43168787/31f044e0-6ace-464f-9aa0-0ae328dc09fb)

### Steps To Reproduce

1. Run playwright test script clicking a radiobutton
```typescript
const radioButton = await page.getByRole("radio", {name: "Gutt"});
await radioButton.click();
```

### Additional Information

I will guess that this also fails for Jest/Vitest/Cypress when using [Testing-library](https://testing-library.com/).
```
expect(screen.getByRole("radio")).toBeVisible()
```
The difference here is that unit tests not run in the browser usually don't check if the element is visible before clicking.

**Comment by mrosvik** [comment]
Thanks for reporting this, we will look into it!

**Comment by mrosvik** [comment]
It turns out that this requires a little more investigation, so if it is not critical in relation to production for you @lasseklovstad , we will come back to this issue. We are planning some changes to the radio button and will fix it in connection to this.

**Comment by lasseklovstad** [comment]
> It turns out that this requires a little more investigation, so if it is not critical in relation to production for you @lasseklovstad , we will come back to this issue. We are planning some changes to the radio button and will fix it in connection to this.

Hi, thanks for the reply. It is not critical to production. Its possible to work around forcing a click on hidden elements as a temporary fix for testing.
