### ISSUE TITLE
Remove all component-specific tokens in react

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#536]
The following components are using the old --component-specific tokens:

- CheckboxRadioTemplate
- InputWrapper 
- Checkbox
- CheckboxGroup
- FieldSet
- LegacyAccordion and LegayAccordionHeader
- List
- ListItem
- RadioButton
- RadioGroup
- Select
- TextArea
- ToggleButtonGroup

**Comment by mimarz** [comment]
This issue is no longer needed as we are doing this as part of our "improvements" issues for the components when going from "Altinn" to "Felles" components
