### ISSUE TITLE
Tag: Should use token for border-radius

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#544]
If there are conflicts between `Core.json` and `Semantic.json` the conflicting properties do not be generated to tokens.css. They are removed/ignored by a filter function defined in the `css/variables-scoped-references` transformer.

**Comment by framitdavid** [comment]
We should link to the TagComponent from the components list that shows the current status. https://digdir.github.io/designsystem/?path=/docs/komponentoversikt--docs
