### ISSUE TITLE
Typography: Using H2 with size xsmall does not add correct spacing, only size.

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#546]
Alert har for mye space under tittel. Det er trolig fordi den er en H2, men den har størrelsen til en xsmall (H5). Men den beholder paddingen til H2... Den skulle egentlig tatt spacingen til xsmall(H5) også.

![Image](https://github.com/digdir/designsystem/assets/1464915/19310a95-291b-4e5e-b0c9-8fe8fbc30399)

**Comment by framitdavid** [comment]
@mrosvik Within the code it looks like all the `<Heading>` uses the same spacing (--fds-spacing-5) regardless of the heading level 1, 2, 3, 4 or 5.  The spacing is implemented with a `margin-bottom: var(--fds-spacing-5). I could not find any margin-bottom on the Typography component within Figma. Let's talk about this issue after the weekend. :)

**Comment by mrosvik** [comment]
Heading xlarge = margin-bottom: spacing-6
Heading large = margin-bottom: spacing-5
Heading medium = margin-bottom: spacing-4
Heading small = margin-bottom: spacing-3
Heading xsmall = margin-bottom: spacing-2
Heading xxsmall = margin-bottom: spacing-1
