### ISSUE TITLE
Component: Select (not synced with design)

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#55]
### Description of the bug

1) Tab-focus (purple outline) should only show when using keyboard navigation, not when you activate the select-box.

![image](https://user-images.githubusercontent.com/1464915/212263426-f79fc3ab-b2c8-4871-8009-91ce9f601556.png)

2) When resizing window (storybook) the component seems to be a fix width and does not scale. 
![image](https://user-images.githubusercontent.com/1464915/212263574-f39ee39f-9b66-4c9b-bc8c-d8516e45d6d0.png)

3) There should be two sizes: Medium with 18px, and Small with 16px font size both for label, description and options. Seems like the options is larger than the selected text. 
![image](https://user-images.githubusercontent.com/1464915/212263801-039a7f0e-1c8b-4b8a-8f44-6ec58ed803c8.png)

4) The X on the chip is not centered 
![image](https://user-images.githubusercontent.com/1464915/212264237-2e4034db-6573-47bc-bab7-3a9c25a6a542.png)

5) Should be named "Single select" and "Multi select" instead of "Flervalgsmeny" and E"nkel"
![image](https://user-images.githubusercontent.com/1464915/212269787-d98dbd7c-606e-43e3-873a-1b9deae6f97b.png)

See Figma sketches for correct design: 
https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/DDS---Core-Components?node-id=7577%3A43639&t=xlYDTn7VXmpckqPy-1

### Steps To Reproduce

Go to https://digdir.github.io/designsystem/?path=/story/kjernekomponenter-select-flervalgsmeny--normal to reproduce the behavior.

**Comment by TomasEng** [comment]
Just some remarks on points 2 and 5:
2 (resizing): This is only an issue in Storybook. The actual component defaults to the width of its container. To make the example in Storybook look more realistic, there is an invisible container with a fixed width around the select box.
5 (naming): We have chosen to use Norwegian as the default language in Storybook, except from components, which are referred to by their name in the code. Single select and multiple select are just variants of the same component, `Select`, hence the choice of menu item names.

**Comment by TomasEng** [comment]
Point 1 will probably be solved by #129.

**Comment by mrosvik** [comment]
Not relevant anymore, since we have updated design in Figma. New issue will be created with updated design.
