### ISSUE TITLE
Do not render a label for RadioButton

### ISSUE THREAD

**Issue by mikaelrss** [digdir/designsystem#555]
### Description

We want to be able to set a `label` for `RadioButton` from the outside, to make sure that outside users can control how a custom `RadioButton` behaves. 

The example below shows a case where we wish to wrap `RadioButton` in a `Card`. Because the `RadioButton` always renders a `label`, we are unable to provide a focus styling on the card component. The entire card is also not clickable. 

![image](https://github.com/digdir/designsystem/assets/26043795/f11e59fe-84aa-4d78-8ace-0452092bee49)

Giving an optional `prop` to disable rendering of a `label` will make it possible to implement such behaviour for a parent component. 

After discussing with @framitdavid and @Febakke, we decided to not do a full refactor of `RadioButton` and `Checkbox`-components right now, although that would be an ideal solution.

**Comment by framitdavid** [comment]
The PR was closed without merge because these changes are not necessary to achieve what @mikaelrss wanted to. :)
