### ISSUE TITLE
Enable the use of preventDefault for the components RadioGroup, CheckBoxes, and Select

### ISSUE THREAD

**Issue by lassopicasso** [digdir/designsystem#563]
### Description

The purpose is to provide a confirmation prompt where the user must confirm before the change is applied to these components, similar to how alertOnDelete works for deleting rows in a repeating group.

The current challenge is that onChange for, for example, RadioGroup returns a value of type string instead of React.ChangeEvent. This prevents us from stopping the event to mark the radio button that the user clicked on before it is confirmed.

I have also been working on adding this into the upload components; 

https://github.com/Altinn/altinn-design-system/assets/74791975/acb4d974-4f97-4952-90ea-5057f92cde34

### Tasks

-  RadioGroup
-  Select
-  CheckboxGroup

### Additional Information

Request from SSB : https://github.com/Altinn/app-frontend-react/issues/1233

**Comment by framitdavid** [comment]
Thanks for creating the issue! 🙌 

We are working on re-design and documentation for new Radio/Checkbox components and they are prioritized for v1. The new components will support the default event to be returned within the callbacks ex. onChange. 

However, I'm not sure if this is possible to do with our select unless you are using our native-select component which has a native event to be returned within the callbacks.

**Comment by mimarz** [comment]
Will instead resolve this issue when new Radio and Checkbox component are released :)
