### ISSUE TITLE
Modal: Design component in Figma

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#585]
### Design requirements
- Should be displayed at the center of the viewport to ensure its visibility.
- Should have a visually appealing design that adheres to the overall application's theme.
- Should support different sizes and be resizable to accommodate various content lengths.

### Design tasks

- [x] Design is fully specified in Figma
  - [x] Design component with all relevant states
  - [x] Do a accessibility test of the sketches
  - [x] Functionality/animation is described and prototyped if relevant    
  - [x] If there are used any svgs in this component is it available for the developer? 
  - [x] Link to Figma design: https://www.figma.com/file/V4dzf3m1sapmU048OQnu7L/Arbeidsomr%C3%A5de%3A-Felles-komponenter?type=design&node-id=2%3A87686&mode=design&t=fQRvYOsXaSqvldYa-1
  - [x] Pasted screenshot from Figma below :point_down:
  

![Image](https://github.com/digdir/designsystem/assets/13560642/6a381155-99a2-4ffd-b517-783c808a4e19)

**Comment by Febakke** [comment]
Nydelig! @Thuneer 👏

Jeg gjorde noen endringer
- ✅ Endret navn på kompontent til Modal 
- ✅ Fjernet right container i footer. (var tom)
- ✅ Endret navn på slot2 propertien til Swap slot

Leverer vi en backdrop som følger med komponenten i koden? Burde vi gjøre den litt mer tilgjengelig på et vis i Figma? Ser at den ligger som et eksempel.

**Comment by Thuneer** [comment]
La til ein beskrivelse i Modal komponenten om at komponenten må brukes i lag med ein backdrop.
