### ISSUE TITLE
Testing component synergy

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#588]
Testing the design and patterns of the component library together. Then create a list of improvement suggestions.

Link to testing environment: [Figma](https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=16516%3A64273&mode=design&t=xwsbrygM7CT9Mv5y-1)

**Comment by mrosvik** [comment]
https://www.figma.com/file/5x3i5T512RVrbUDn8PW4H6/Eksempler?type=design&node-id=2%3A3799&mode=design&t=fVRPnEU6nPoFFru6-1
