### ISSUE TITLE
Designsystemet på Brukerrådet

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#589]
> **Opptak: 18.august**

Samtalepunkter vi skal innom:

- Grunnleggende problem:
    - Kostnader for utvikling og forvaltning (evt. ingen garanti for forvaltning når det er så fragmentert)
    - Kvalitetskrav som ikke oppfylles
    - Forskjellig hvordan vi presenterer tjenester for publikum -  det er ikke gjenkjennelig på tvers

- Løsning
   -  Felles designsystem og hva det løser
   - Forutsetningser for å komme dit

**Comment by mrosvik** [comment]
@Camulos

**Comment by Camulos** [comment]
Dette blir bra!

**Comment by Camulos** [comment]
Temaer / talkpoints:

Felles behov / problemstilling:

- Kostnader med utvikling og forvaltning av digitale tjenester
- Kvalitetskrav, slik som universell utforming oppfylles ofte ikke
- Opplevelsen er veldig forskjellig

Designsystem som del av løsningene:

- Designsystem kan gi kjempegevinster gjennom 30-80% redusert tidsbruk på ny kode i front-end
- Innebygget kvalitet
- Likhet på tvers av flater i offentlig sektor

Forutsetter:

- Må investere (alle må bidra) gjennom dedikerte resurser
- Må bygges av dem som skal bruke det
- Må inkludere designsystem og kvalitetsarbeid i all prosjektestimering

Hva gjør de i hver enkelt etat som har designsystem:

- bruker 3-15 millioner kroner i året på designsystem forvaltning (dedikerte team på 3-10+)
- rift om samme resurser i markedet?
- løser ting internt med frister og leveranser knytta til interne prosjekter
- alle har ikke samme kompetansenivå?

Hvorfor gjøre det sammen da?

- redusere kostnad per virksomhet, dele byrden / investerings og forvaltningskostnaden?
- innebygget kvalitet
- ting blir likheter på tvers?

Andre spørsmål:
- trenger gode bindeledd mot de som skal bruke designsystemet (lett å ta i bruk, lett å bidra, lett å jobbe inn behov)
- kan det settes krav til dedikerte designsystemdeltakere i alle store offentlige digitaliseringsprosjekter?
- kan det stilles krav til større etater om å avgi teammedlemmer?

Grunnleggende om hvordan offentlig sektor planlegger og gjennomfører prosjekter, hvordan finanseres ting, hvordan finansierer vi noe felles som ikke bare er at prosjekt med sluttdato?

**Comment by LisLonning** [comment]
Supert! Takk Roy. 😊

Med vennlig hilsen Lis

From: Roy Halvor Frimanslund ***@***.***>
Date: Monday, 26 June 2023 at 09:45
To: digdir/designsystem ***@***.***>
Cc: Lonning, Lis Madeleine ***@***.***>, Assign ***@***.***>
Subject: Re: [digdir/designsystem] Designsystemet på Brukerrådet (Issue #589)
[ Ekstern e-post ]

Temaer / talkpoints:

Felles behov / problemstilling:

  *   Kostnader med utvikling og forvaltning av digitale tjenester
  *   Kvalitetskrav, slik som universell utforming oppfylles ofte ikke
  *   Opplevelsen er veldig forskjellig

Designsystem som del av løsningene:

  *   Designsystem kan gi kjempegevinster gjennom 30-80% redusert tidsbruk på ny kode i front-end
  *   Innebygget kvalitet
  *   Likhet på tvers av flater i offentlig sektor

Forutsetter:

  *   Må investere (alle må bidra) gjennom dedikerte resurser
  *   Må bygges av dem som skal bruke det
  *   Må inkludere designsystem og kvalitetsarbeid i all prosjektestimering

Hva gjør de i hver enkelt etat som har designsystem:

  *   bruker 3-15 millioner kroner i året på designsystem forvaltning (dedikerte team på 3-10+)
  *   rift om samme resurser i markedet?
  *   løser ting internt med frister og leveranser knytta til interne prosjekter
  *   alle har ikke samme kompetansenivå?

Hvorfor gjøre det sammen da?

  *   redusere kostnad per virksomhet, dele byrden / investerings og forvaltningskostnaden?
  *   innebygget kvalitet
  *   ting blir likheter på tvers?

Andre spørsmål:

  *   trenger gode bindeledd mot de som skal bruke designsystemet (lett å ta i bruk, lett å bidra, lett å jobbe inn behov)
  *   kan det settes krav til dedikerte designsystemdeltakere i alle store offentlige digitaliseringsprosjekter?
  *   kan det stilles krav til større etater om å avgi teammedlemmer?

Grunnleggende om hvordan offentlig sektor planlegger og gjennomfører prosjekter, hvordan finanseres ting, hvordan finansierer vi noe felles som ikke bare er at prosjekt med sluttdato?

**Comment by mrosvik** [comment]
Opptaket ble utført fredag 18. aug.
