### ISSUE TITLE
Empty button error in Select component

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#600]
### Description of the bug

The ```<Select />``` component gets the following error in ```Wave```. This happens for an empty field, and for each new element you select, one more error is added. 

<img width="216" alt="Screenshot 2023-06-27 at 11 03 05" src="https://github.com/digdir/designsystem/assets/133344438/d3d0b89e-48f0-4b1a-ae3a-95a0a656bd63">

### Steps To Reproduce

1. Use the ```<Select />``` component in your app. 
2. Open ```Wave``` 
3. The error is there. 
4. Close ```Wave``` 
5. Select a few options from the ```<Select />``` component. 
6. Open ```Wave```
7. There are now as many errors as elements selected plus 1.

**Comment by framitdavid** [comment]
Thanks for creating this issue! 👏 💯 I follow up on this one with the core team. If you want to, please feel free to commit a pull request with a fix. 👍

**Comment by framitdavid** [comment]
@WilliamThorenfeldt I have tried to reproduce this error within Storybook but it seems to work as expected without errors. Can you please give me some more information about which app you tested? 😄

**Comment by WilliamThorenfeldt** [comment]
@framitdavid I tested this using Chrome. I get the error when I have elements selected. Below are screenshots of which buttons Wave says the error is in. It gives 1 error for every element selected, and it only gives the error for the component when the ```multiple``` props is turned on. 

<img width="98" alt="Screenshot 2023-07-28 at 09 01 16" src="https://github.com/digdir/designsystem/assets/133344438/4d961d8f-7745-4266-80fc-8d02868b7dc6">
<img width="158" alt="Screenshot 2023-07-28 at 09 01 07" src="https://github.com/digdir/designsystem/assets/133344438/08de34ac-c2fd-454e-a077-37b51a8ec2a2">

**Comment by mimarz** [comment]
This looks be fixed in our `Combobox` which replaces `Select` #1090.

I tested using [WAVE](https://wave.webaim.org/) extension without getting any errors.
