### ISSUE TITLE
Considering to extend CSS with PostCSS

### ISSUE THREAD

**Issue by framitdavid** [digdir/designsystem#604]
There are a few features that are not yet supported by default. Today, we encountered an issue with the rgba() method. By default, CSS does not support rgba(#hexcode, opacityValue). Therefore, we need to convert the #HEX to RGB colours.

However, we can avoid the need to convert #HEX to RGB colours by utilizing PostCSS or CSS preprocessors. These tools provide additional functionality and support for rgba() with #HEX and opacity values.

However, I do not want to just implement a tool without investigating the pros and cons between them. We should also wait for @mimarz to be back from holidays. 

With the small research I have already done, I think PostCSS looks great - modular and small.

**Comment by framitdavid** [comment]
If the UX/UI can use another color palette instead of opacity, then we do not need to support RGBA within our CSS.

**Comment by mrosvik** [comment]
Related to https://github.com/digdir/designsystem/issues/606

**Comment by mimarz** [comment]
We should not fix this with PostCSS as its to "late" in the pipeline as the changes would only apply to the react package. This would leave out our users who are using the tokens directly. 

Changes to color unit would needs to be done in the token transformation step. Style dictionary and Token studio already have transformers for this feature.
