### ISSUE TITLE
Use of Paragraph in Button component causes problems in cypress testing

### ISSUE THREAD

**Issue by allinox** [digdir/designsystem#684]
### Description of the bug

(Not sure if 'bug' is the right word, but it's something)

Recent changes to the Button component introduced the use of the Paragraph component inside the button element, packaging the button's children (usually text) as a way to provide them with dynamic typography.

Unfortunately, this seems to cause issues with cypress testing.

In our project, we want our tests to interact with our components the way a user would do, for example by pressing the button with the text 'Apply' on it. This used to work well through the much used command `cy.get('button').contains('Apply').click();` but now that the text is nested inside the paragraph, this command causes an error in cypress, because the element it attempts to click "is being covered by another element". In order to press the button, you have to instead access the parent element before clicking, so that cypress is able to press the button directly. This works, but it feels a bit cumbersome for such a frequently used and simple thing as a button click.

A similar issue also arises when assessing attributes like checking if the button is aria-disabled.

### Steps To Reproduce

Assuming the button that is being tested contains the text 'Apply', run the following line in a test in cypress:

`cy.get('button').contains('Apply').click();`

**Comment by mimarz** [comment]
Thanks for reporting this! We'll have a look at it in not to long hopefully :)
