### ISSUE TITLE
Storybook: Endre design av core changelog

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#69]
Endre design av core changelog til å bli mer lesebar + legge til ikoner for bug og feat.

**Comment by Thuneer** [comment]
Ser changeloggen greit ut?

![Image](https://user-images.githubusercontent.com/13560642/214280863-47ab8f84-ea9f-4ff8-bab6-2fbb33ff1005.png)

**Comment by mrosvik** [comment]
Ser bra ut 🙌
