### ISSUE TITLE
Vercel hosting payment (designsystemet.no)

### ISSUE THREAD

**Issue by Thuneer** [digdir/designsystem#696]
- [x] Kontakta drift om dei kan hjelpe oss med finansiering
* Drift tok kontakt med Digdir sin lisensaktør og sa at ein i designsystem teamet må ta møte med dei direkte.

- [x] Kontakte lisensaktør og be om eit møte for å sjå på finansiering
- [ ] Har kontakta Moonsoft og satt opp møte 10.08

**Comment by mimarz** [comment]
Driftes Moonsoft
