### ISSUE TITLE
Pattern: Form required fields

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#729]
How do we signify required form fields? 

- Asterisks on label? 
- "required" text after label? 
- Preface that all fields in a form are required?
- If all form fields are required by default, then only mark optional fields?

There are multiple solutions and aspects to this we need to figure out in terms of which form patterns we recommend and what we implement in our components.

Discussion in Slack: https://altinndevops.slack.com/archives/C0510HS2RRR/p1692338419113949

**Comment by Camulos** [comment]
Først de aktuelle reglene:
- WCAG: 1.1.1: Ikke-tekstlig innhold: Gi brukeren et tekstalternativ for innhold som ikke er tekst.
- WCAG: 3.3.2: Ledetekster eller instruksjoner: Det vises ledetekster eller instruksjoner når du har skjemaelementer som må fylles ut.
- Elmer: 3.6 Frivillige felter: Hvis det er frivillig å besvare et spørsmål skal dette framgå tydelig.

Vi har også et WCAG suksesskriterie om at en skal vise til mer enn farge, form etc for å veilede...

I BR har dette resultert i følgende krav til løsning:
Vi forteller med tekst hvilke felter som er påkrevde eller ikke-påkrevde. Det betyr ikke at det skal stå påkrevd på alle påkrevde felt og ikke-påkrevd på alle frivillige felter i samme løsning, men en av delene skal være merket med tekst i nærheten av feltet / label, vanligvis etter eller som del av label.

Dersom en likevel vil bruke stjernetegnet, så skal det også være forklart hva stjernetegnet betyr et sted på hver eneste side det brukes, dette fordi det er det som er poenget med stjernetegnet, å fortelle at her er det en notis som står feks i bunnteksten som sier noe mer om dette temaet eller gir nyttig ekstrainformasjon (tenk en fotnotis).

Så min mening: bruk tekst som del av label og merk enten det ene eller det andre (påkrevd / ikke påkrevd).

**Comment by mrosvik** [comment]
Vi må komme tilbake til å lande felles retningslinjer for hvordan vi skal håndtere dette i ulike situasjoner. 

SSB bør involveres da de har hatt meninger om dette i forbindelse med skjemaer i Altinn Apps. @Febakke sjekker med dem.

**Comment by mrosvik** [comment]
Det jobbes nå med å lande felles mønstre for dette sammen med Nav, Skatteetten, Oslo kommune, Brreg, SSB. https://github.com/digdir/designsystem/issues/844

**Comment by mrosvik** [comment]
Forslag: https://storefront-pr-1157.dev.designsystemet.no/monstre/obligatoriske-og-valgfrie-felt

**Comment by mrosvik** [comment]
Artikkelen kan ses her: https://www.designsystemet.no/no/patterns/required-and-optional-fields
