### ISSUE TITLE
Chip looks strange when used with long labels on small screens

### ISSUE THREAD

**Issue by allinox** [digdir/designsystem#747]
### Description of the bug

![image](https://github.com/digdir/designsystem/assets/22012997/697c4c46-34da-4cc7-bc74-0e4d6f40ff93)

When using removable chips for filtering, the labels on them can sometimes become somewhat long. And if there is enough space for it to keep it all on one line, this doesn't seem to be a problem.

But on small screens, where the labels break up into two lines, it looks like the chip just kind of ..breaks.
The padding doesn't seem to be additive to the content, so the text feels pretty cramped. And when hovering over the chip, it looks like the red x-button doesn't adjust to the increased height.

### Steps To Reproduce

1. Render a Chip component with about 3 to 6 long words as the label
2. Resize the screen to about 315px
3. Observe that the chip seems to bee cramped compared to one with only one word

**Comment by mimarz** [comment]
Thanks for reporting this! We'll have a look at it in not to long :)

**Comment by mimarz** [comment]
Can one of you have a look at this when you have the time? @framitdavid @TomasEng

**Comment by TomasEng** [comment]
I'll have a look tomorrow 🙂
