### ISSUE TITLE
Increase contrast on description

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#771]
We have gotten feedback that the color on our description is hard to read. It does not break any WCAG success criterion, but I see no reason to not increase the contrast to make it more readable. 

- [ ] Look into a darker color for description text
- [ ] Change tokens

**Comment by mrosvik** [comment]
Det vå være en forskjell på label og description. Vi må se nærmere på hvordan løses dette.

**Comment by Febakke** [comment]
The problem is not in the design system but in Altinn Apps. Created a new issue in the correct repo and closing this.
https://github.com/Altinn/app-frontend-react/issues/1471
