### ISSUE TITLE
Combobox: React component

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#772]
As part of work on developing "Autocomplete" we want to do exploration work on create a Combobox component first which support single select and autocomplete search using Floating-ui library.

What this component ends up being called, or how we use remains to be seen.

Notes:
- https://www.w3.org/WAI/ARIA/apg/patterns/combobox/
- https://floating-ui.com/docs/useListNavigation
- https://codesandbox.io/s/fragrant-water-bsuirj?file=/src/App.tsx
- https://a11y-guidelines.orange.com/en/articles/autocomplete-component/
- https://storybook.eds.equinor.com/?path=/docs/inputs-autocomplete--docs

**Comment by mrosvik** [comment]
Experimental combobox. There will be a new issue related to continue work on this.
