### ISSUE TITLE
React: Use the new global action colors for action colors that should not be changed based on brand

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#780]
See: #778

**Comment by mrosvik** [comment]
Vi må diskutere om vi skal beholde "Input"-tokens eller om det hodler med action-dark



![Image](https://github.com/digdir/designsystem/assets/1464915/d8449e38-fed1-4482-a59b-eabe560c5425)

**Comment by mrosvik** [comment]
Components that should be updated: 

- Accordion should use global action color for hover text/icon instead of primary
-

**Comment by mimarz** [comment]
This will be fixed by #873
