### ISSUE TITLE
Kartlegge eksisterende offentlige designsystem

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#785]
SSB: https://design.ssb.no/
SIKT: https://designsystem.sikt.no/
Lånekassen: https://calm-hill-068549003.azurestaticapps.net/?path=/docs/introduction-welcome--docs
Utdanning no: https://design.utdanning.no/
Arbeidstilsynet: https://design.arbeidstilsynet.no/?path=/docs/dokumentasjon-velkommen--page
Kartverket: https://kartverket.github.io/kvib/storybook
Miljødirektoratet: https://design.miljodirektoratet.no/
Vestfold og telemark fylkeskommune: https://komponenter.vtfk.no/?path=/docs/dokumentasjon--designsystem
Integrerings og mangfolddirektoratet: https://www.imdi.no/om-imdi/designsystem/
DFØ: https://komponenter.dfo.no/ / https://dfo.no/om-dfo/dfos-profilveileder/skal-du-utvikle-digitale-losninger-dfo
Domstolene: https://design.domstol.no/987b33f71/p/74a507-domstolenes-designsystem
Innovasjon norge: https://company-139306.frontify.com/d/YokG7g2Ch3dy/brand (Bak innlogging)
Posten og Bring: https://hedwig.posten.no/
Entur: https://design.entur.no/
Helsenorge: https://github.com/helsenorge/designsystem
Statsforvalteren: https://bak.statsforvalteren.no/storybook/index.html?path=/story/introduction--page
Lillestrøm kommune: https://design.lillestrom.kommune.no/guide/
Nasjonal Digital Læringsarena: https://designmanual.ndla.no/?path=/story/velkommen--velkommen 
DHIS2/UiO: https://ui.dhis2.nu/demo/?path=/story/table--static-layout 
NTNU? https://design.online.ntnu.no/?path=/docs/forms-toggle-switch--default-story 
Politiet: https://www.politiet.no/design/
Fiskeridirektoratet har, men finner ikke lenken.
Forsvaret har, men finner ikke lenken.
Statens vegvensen har, men finner ikke lenken.

**Comment by mimarz** [comment]
Move this to https://github.com/digdir/designsystem/wiki

**Comment by mrosvik** [comment]
Moved to wiki : https://github.com/digdir/designsystem/wiki/Kartlegge-eksisterende-offentlige-designsystem ✅
