### ISSUE TITLE
Checkbox.Group z-index bug

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#789]
### Description of the bug

The ```Checkbox.Group``` component's checkboxes are on top of the modal (only the boxes, not the text). I suspect it has something to do with the z-index. 
![image](https://github.com/digdir/designsystem/assets/133344438/1cabac4a-1965-46cf-b272-0717afced949)

### Steps To Reproduce

1. Create a component with Checkbox.Group and create a modal. 
2. Open the modal
3. View that the checkboxes are on top of the modal

**Comment by mimarz** [comment]
Abit late to the party, but its been a busy week 🙈 

We'll have a look very soon! 

Are you able to provide an example in [codesandbox](https://codesandbox.io/)? What Modal component did you use, just native or?

**Comment by WilliamThorenfeldt** [comment]
Here is a [link](https://codesandbox.io/s/hardcore-lumiere-k63ysx?file=/src/App.tsx) to a codesandbox demonstrating the bug :) 
I used [react-modal](https://github.com/reactjs/react-modal).
