### ISSUE TITLE
SEO: Check if old design system (patternlab) is  removed from google search

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#8]
Remove this: https://altinn.github.io/DesignSystem/ from google search.

Add a PR to https://github.com/Altinn/DesignSystem 

metatag i header som gjør at den ikke indekseres i søkemotorer:

`<meta name="robots" content="noindex">`

**Comment by mrosvik** [comment]
Done: https://github.com/Altinn/altinn-design-system/pull/273

**Comment by mimarz** [comment]
this should now be done as we unpublished patternlab
