### ISSUE TITLE
Checkbox fungerer ikke med next.js

### ISSUE THREAD

**Issue by ohatland** [digdir/designsystem#812]
### Description of the bug

Checkbox vises ikke som beskrevet i eksemplet.
Når boksen er checket kommer det ett hvitt kryss på hvit bakgrunn, hover effekt fungerer heller ikke

### Steps To Reproduce

1. Opprett ett nytt next prosjekt med `npx create-next-app@latest`
2. Fjern all styling og boilerplate
3. Installer npm pakken med desigsystemet `npm install @digdir/design-system-react`
4. Importer Checkbox eksempel fra https://digdir.github.io/designsystem/?path=/docs/felles-checkbox-group--docs

### Additional Information

Versjoner jeg bruker:
node: 18.12.1
next: 13.4.19
react: 18.2.0

Bilde av feilen:
![image](https://github.com/digdir/designsystem/assets/18251869/9ed09b8a-460d-4555-b08d-9282bcfd17e7)

**Comment by mimarz** [comment]
Takk for for tilbakemeldingen! 

Ja, dette er et problem med Next 13 og css modules som vi bruker 🙈. Den får ikke med seg cssen til komponenten i payloaden. Vi ønsker å forbedre/endre på dette, men ikke fått kommet så langt enda...

> Next.js 13 introduces a new app/ directory / folder structure. By default it uses Server Components.

Kunne du testet med å bruker `"use client"` i toppen av filen? du bruker komponenten for å se om det funker bedre?
