### ISSUE TITLE
Add missing `ErrorMessage` size `large`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#837]
After examining components that are used together we identified that `ErrorMessage` is missing a size `Large` to pair with other form text options. 

This will need to be added to Figma, tokens and React.

**Comment by mimarz** [comment]
Could one of you guys add this soon-ish? @mrosvik @Febakke `ErrorMessage` currently defaults to medium size when large is selected for the new `Textfield`.

**Comment by mrosvik** [comment]
yup.

**Comment by mrosvik** [comment]
https://github.com/digdir/designsystem/pull/839

**Comment by mimarz** [comment]
Is this added in Figma? @mrosvik @Febakke

**Comment by Febakke** [comment]
Seems like it is: https://www.figma.com/file/vpM9dqqQPHqU6ogfKp5tlr/Felles-komponenter?type=design&node-id=20750%3A76353&mode=design&t=t24ZXTXKIWpqxnad-1
