### ISSUE TITLE
Sorter (reorderable list) - component that allows the user to specify/change order of subcomponents/content

### ISSUE THREAD

**Issue by Camulos** [digdir/designsystem#847]
### Describe the component

The user are presented with a number of options or are tasked to add options themselves. Afterwards the user are allowed to change the order of the options presented (or added).

Example in one of our Altinn projects (Brukervennlige registertjenester, "lag nytt enkeltpersonsforetak" ) the user is tasked to selecting an main activity and 0-4 additional activites for their new business. It is very important that we know whatever activity is the main one listed first, but the user might want to change the order after they have selected/added up to 5 different activities. In this case, for each line inside this component there is one select-field and one button to remove the line.

### If you have any examples or similar components feel free to include links or screenshots here

Topic is discussed a bit here:
https://www.darins.page/articles/designing-a-reorderable-list-component

**Comment by mrosvik** [comment]
Not sure if this is a component for the design system? Have we seen any similar component in existing design systems? Maybe this is a task for Altinn 3 instead? @Febakke

**Comment by Febakke** [comment]
Created a new issue [here](https://github.com/Altinn/app-frontend-react/issues/1547)
If we conclude that we need a new component and that it should be handled in the design system we will reopen this.
