### ISSUE TITLE
Add "use client" to dist bundle for react package

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#860]
Currently our react package crashes when used in combination with React Server Components. 

As a hotfix to prevent crashing we want to add ["use client"](https://react.dev/reference/react/use-client) to our dist bundle to prevent crashes now. 

Better SSR support will be added in the future.

**Comment by Barsnes** [comment]
We need to add `banner: 'use client'` to the rollup output config for this to work. Ref:[This issue]( https://github.com/dvtng/react-loading-skeleton/pull/162)

However, our `terser()` plugin removes this banner.

**Comment by Barsnes** [comment]
Terser removing the `"use client"` is an open issue in the terser plugin: https://github.com/terser/terser/issues/1320
I found that Sanity.io uses [this solution](https://github.com/sanity-io/pkg-utils/pull/27/commits/b62f2f4825ec8420b2cf981b0b32b3431ab230a1).
It simply adds this:
```
compress: {
          directives: false,
},
```

This makes it so we still use terser, and SSR works fine.
