### ISSUE TITLE
Storybook: List should have the same size as paragraph

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#905]
The list should not appear smaller than the rest of the text.

![Image](https://github.com/digdir/designsystem/assets/1464915/779a33d5-428a-4e01-aed2-070f4c87ca06)

**Comment by mimarz** [comment]
related to #781 & #670

**Comment by ayobamiseun** [comment]
Hi @mimarz can i work on this i will like to be part of this project.

**Comment by mimarz** [comment]
> Hi @mimarz can i work on this i will like to be part of this project.

Sorry for the late reply, but we are currently not looking for contributions outside of the organisation as we have quite a few things we are working on figuring out and things are changing constantly, so we need to have a localised team. 

Thanks for volunteering atleast!

**Comment by mimarz** [comment]
@Barsnes See if we can use the new `List` component for this in `.storybook/preview.tsx`

**Comment by mimarz** [comment]
This has to be looked at after #781
