### ISSUE TITLE
Implement new changes to `Popover`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#932]
Have a look at https://floating-ui.com/docs/popover#reusable-popover-component

- Remove `PopoverTrigger` component
 - We will use the approach of using `anchorEl` prop for which element to anchor to.
- Just implement the `Popover.Content`
- Same placement options as `Tooltip`
- Support for controlled, `open` as `Tooltip`
- Dismissable on outside click
- By default the popover content is inlined in the dom.
- Make sure new tokens prefixed with `--fds` are used
- Use `types` for types and `forwardRef`, in general the same code standard as our other compoenents.
- Suggest using `z-index: 1500` #500 
- Will probably need support for Portals vis FloatingPortal, but lets asses if this needs to be included in the first version we are making now or not

**Comment by Barsnes** [comment]
`defaultOpen` is not needed, since you can just set the initial value for your `open` state to true
