### ISSUE TITLE
Documentation/guide for when and on what component-mode-height should be used

### ISSUE THREAD

**Issue by Febakke** [digdir/designsystem#937]
Our tokens `component-mode-height`, `component-mode-spacing`and `component-mode-gap`are not easy to know when should be used. I think if we create some guidelines that include examples on what components use them today and why it would be easier for designer to set up their components. 

We also dont have any component-mode for our smaller components like:
* Checkbox
* Radio
* Switch
* Chip
* Tag

**Comment by mimarz** [comment]
We almost don't use the component mode tokens in react components, only `Button` uses `component-mode-height` but there are some issues with this.

**Comment by mimarz** [comment]
Suggest we find a way to not have to use these tokens to reduce complexity and number of tokens.

**Comment by Febakke** [comment]
We have decided and implementet to only use sizing tokens and remove component-mode-height and the compact set completely. This was do reduce the complexity. 
There is a overview of our sizing tokens used in our Figma component library 
<img width="790" alt="Skjermbilde 2024-01-02 kl  14 27 06" src="https://github.com/digdir/designsystem/assets/33222679/9d1aa75a-8ee6-4da0-bfaf-c4368703b691">
