### ISSUE TITLE
Link: make a link look like a Button

### ISSUE THREAD

**Issue by mlqn** [digdir/designsystem#939]
### Description

I'm not sure if this feature already exists, but would it be possible to make a link look like a button using the `Link` component?

Here are examples from Altinn Studio, where we have links that look like buttons:
<img width="270" alt="Screenshot 2023-10-14 at 17 55 04" src="https://github.com/digdir/designsystem/assets/24462611/84552c2a-a710-4650-885d-7e1f36aaa70f">

<img width="811" alt="Screenshot 2023-10-14 at 15 42 28" src="https://github.com/digdir/designsystem/assets/24462611/5eb70479-787e-45aa-9ce8-34b76977271e">

**Comment by mimarz** [comment]
Good morning! 

We aim to provide polyformism for most of our components, which means you can change the underlying html element. 

We added this [feature to Button](https://github.com/digdir/designsystem/pull/926) last week actually in release 0.31.0 of react!

You can now use `as` on `Button` to change it into an `a` element like so: `<Button as='a'>Send me somewhere!</Button>`
