### ISSUE TITLE
Expandable radio buttons

### ISSUE THREAD

**Issue by mrosvik** [digdir/designsystem#94]
- This is a need from OED-team, with sketches and prototype made by Cecilie: https://www.figma.com/proto/oBtm6UxIjZzOg0xzJganiL/OED-desktop-2023?page-id=0%3A1&node-id=298%3A19354&viewport=16879%2C6599%2C0.61&scaling=min-zoom&starting-point-node-id=298%3A19354&show-proto-sidebar=1 
- Will be user tested in OED.
- This should probably be a variant / extension of the existing [Radiobutton component](https://github.com/orgs/digdir/projects/3/views/4?pane=issue&itemId=18823880)
- Example of expandable radiobutton from other design systems: https://design.entur.org/komponenter/skjemaelementer/radio-panel

![image](https://user-images.githubusercontent.com/1464915/214504406-484f6225-3c0f-4507-b30a-929c1c508060.png)

**Comment by mrosvik** [comment]
OED solved this with a help-text-component instead.

**Comment by mimarz** [comment]
This feature its possible now for our users today by using the `onChange` handle to see which option is checked and enabling description for that option. However, not sure how this will be handled by screen readers. Needs to be tested.

**Comment by mimarz** [comment]
Meeting 31.10.23

We will not solve this in the designsystem as this is to domain specific
