### ISSUE TITLE
Removable chip has wrong background color

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#943]
Reported in on our slack: https://designsystemet.slack.com/archives/C05RF86A3K7/p1697448518707889

The `ChipBase` styling is overriding the style passed from Removable chip.

Notes:

Works fine locally and in storybook but not downstream.
Tested downstream here: https://codesandbox.io/s/charming-shadow-qvkcqr?file=/src/App.tsx
The bug is probably due to the fact that `ChipBase` css is loaded after `Removable` so cascading rules take into effect.

**Comment by mimarz** [comment]
Kinda tempted to re-write the chips to be two separate css files as we will probably need to do this down the line for when we get a css library. 🤔

**Comment by Barsnes** [comment]
> Kinda tempted to re-write the chips to be two separate css files as we will probably need to do this down the line for when we get a css library. 🤔

The css compiler in #924 groups css files by component, so different files would not work.
