### ISSUE TITLE
Test setting font-feature-settings in `inter.css` on CDN

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#946]
The solution for #849 we needed to use `!important`, which is not ideal.

Test if we can rather activate tail-l feature in `inter.css` that we upload to https://github.com/Altinn/altinn-cdn so that users don't need to remember turning on this feature

**Comment by Barsnes** [comment]
@mimarz I tested this by hosting the font locally, with updated `@font-face`.
This did not work, it was still overwritten. Even using `!important` did not work.

**Comment by mimarz** [comment]
As we talked about in DMs, its apparently a dud to use [font-feature-settings in @font-face](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-feature-settings#browser_compatibility) 😢

**Comment by Barsnes** [comment]
Do you want to close this issue, or keep it open until browsers support `font-feature-settings` in `@font-face` ? @mimarz

**Comment by mimarz** [comment]
We can have a look at better support this in issue [#957](https://github.com/digdir/designsystem/issues/957)
