### ISSUE TITLE
Update variant names on `Tag`

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#954]
In #821 we decided to use variant to define style and weight of components. 

`Tag` still uses the old naming scheme for this, and should be updated to use new naming scheme for to match expected style and weight. 

- Change variant `filled` and `outline` to `primary` `secondary`
 - [x] Change in Figma 
 - [x] Change in React component

**Comment by Thuneer** [comment]
Changed variant `filled` and `outline` to `primary` and `secondary` in Figma.
