### ISSUE TITLE
Support native `size` attribute in some of our forms components

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#962]
We are overriding the native [size](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#size) attribute on `Textfield`, ~`Textarea`~ & `NativeSelect` with our own size component size options. 

We should find a way for users to be able to set this as there are use-cases where they might need to do so. 

Maybe make a side-prop for it like Aksel has with `htmlSize`? 🤔

**Comment by Barsnes** [comment]
@mimarz `Textarea` does not have a `size` attribute, but rather `rows` and `cols`.
Do you want these added instead?
Ref.: [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes)

**Comment by mimarz** [comment]
> @mimarz `Textarea` does not have a `size` attribute, but rather `rows` and `cols`. Do you want these added instead? Ref.: [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attributes)

Ah, my bad. Was quick on the typing and didn't check if `textarea` had size or not, I just saw we were omiting it, so just remote the omit then since it doesnt exist. We don't need to add those as we are already exporting the native `textarea` props with `TextareaHTMLAttributes<HTMLTextAreaElement>`
