### ISSUE TITLE
Spinner mismatch on `size` naming

### ISSUE THREAD

**Issue by mimarz** [digdir/designsystem#967]
Our `Spinner` has a mismatch on how `size` is named with different casing and numerals.

Spinner:
```tsx
size: 'xSmall'
  | 'small'
  | 'medium'
  | 'large'
  | '1xLarge'
  | '2xLarge'
  | '3xLarge';
```

Rest of the design system (alternatives found)
```tsx
size: 'xxsmall' | 'xsmall' | 'small' | 'medium' | 'large' | 'xlarge';
```

Suggest we update `Spinner` to follow the same naming convention as the rest of the design system.
This needs to be resolved before bumping this component to "felles"

**Comment by Barsnes** [comment]
@Thuneer Should this be marked as done?

**Comment by mimarz** [comment]
This was done in #970
