### ISSUE TITLE
Open Popover makes screen scroll infinite

### ISSUE THREAD

**Issue by Albertlarsen** [digdir/designsystem#974]
### Description of the bug

https://github.com/digdir/designsystem/assets/31471142/681e7f2e-b384-42cf-88bf-5998eac22e0f

### Steps To Reproduce

1. Open Popover, 
2. Scroll to the right

**Comment by mimarz** [comment]
Thanks for reporting this! 

This is most likely due to it not being inside a [React Portal](https://react.dev/reference/react-dom/createPortal), I was hoping we could avoid this as it adds an additional complexity with SSR, but oh well 🤷‍♂ 

We are using floatin-ui for the portal so this should be solved using their [FloatingPortal](https://floating-ui.com/docs/floatingportal) component. It should be opt-in for rendering to be inside a portal so I suggest having a prop such as `withinPortal` to enable portal rendering.

**Comment by mimarz** [comment]
Do you want to have a look at this @Barsnes ?

**Comment by Barsnes** [comment]
Hey, this does not look good!
I'll have a look at it this week. Would you mind charing the bit of code where this happens as well?

**Comment by Albertlarsen** [comment]
Yeah, no problem 😊

```
          <Popover
              variant={'warning'}
              trigger={
                <Button
                  variant='tertiary'
                  color={delegableChosenServices.length > 0 ? 'danger' : 'first'}
                  onClick={() => setPopoverOpen(true)}
                  fullWidth
                >
                  {t('common.cancel')}
                </Button>
              }
              onOpenChange={() => setPopoverOpen(!popoverOpen)}
              placement={'top'}
              open={popoverOpen}
            >
              <Paragraph>{t('single_rights.cancel_popover_text')}</Paragraph>
              <GroupElements>
                <Button
                  onClick={onCancel}
                  color={'danger'}
                  variant={'primary'}
                >
                  {t('common.yes')}
                </Button>
                <Button
                  onClick={() => setPopoverOpen(false)}
                  color={'danger'}
                  variant={'tertiary'}
                >
                  {t('single_rights.no_continue_delegating')}
                </Button>
              </GroupElements>
            </Popover>

**Comment by Albertlarsen** [comment]
Oh sorry my bad, didn't realize a brand new Popover had been released, haven't gotten to update it yet but I'll do it as soon as possible

**Comment by Barsnes** [comment]
No worries! Test it out when you can, and give me an update if the issue persists
