### ISSUE TITLE
Padding-right issue on Switch

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#979]
### Description of the bug

There is some padding on the right side of the Switch which prevents the component from being aligned in the center of my box:
<img width="175" alt="image" src="https://github.com/digdir/designsystem/assets/133344438/b898f7a8-3341-4a4e-a28e-1b80aa2c0733">

### Steps To Reproduce

1. Use the Switch component inside a div
2. Add a border to the div and make it the size of the switch

**Comment by Barsnes** [comment]
Hello! Thanks for the bug report.
It seems like this happens because the `Switch` uses css grid, with a gap, and the grid is hard coded to two columns in the css. So when you don't have any children or a description this happens.
I will fix this issue, since this should not happen.

**Comment by mimarz** [comment]
Good morning! Just curious how have you solved the labeling the Switch in this use case? @WilliamThorenfeldt
