### ISSUE TITLE
Padding bottom on Select component

### ISSUE THREAD

**Issue by WilliamThorenfeldt** [digdir/designsystem#981]
### Description of the bug

There is some padding on the bottom of the Select which prevents the component from being aligned in the center of my box:
![image](https://github.com/digdir/designsystem/assets/133344438/b7b1f469-a5e3-4149-bacf-abe19b88298d)

### Steps To Reproduce

1. Use the Switch component inside a div
2. Add a border to the div and make it the size of the switch

**Comment by Barsnes** [comment]
Hello, and thanks for the bug report! This is probably similar to the issue in #979. I'll take a look at this
